elfmz/far2l

WinPort/APIRegistry.cpp
Теперь farftp и netbox может удалять хосты.
=> fix RegDeleteKey with values (farftp and netbox now deletes hosts correctly)

_All/_All.project, far2l/execute.cpp
Уже давно вроде как заголовок #/bin/bash для шел скриптов не нужен, они по дефолту таковыми считаются. В mc и дефолтном терминае такие скрипты стартуют. Фикс позволяет их запускать.
=> fix shell scripts without '#' header

far2l/execute.cpp
Выяснил почему цвета не отображались. Из-за отсутствия ключа interactive, .bashrc вылетает сразу же и не устанавливает переменные окружения для цветов, а то что там setenv() перед этим делали bash все обнуляет.
Теперь почти все отсюда https://github.com/elfmz/far2l/issues/9 работает, остался $PS1, но не знаю насколько он нужен.
=> fix console utilities colors output and .bashrc processing

colorer/src/pcolorer2/FarHrcSettings.cpp, far2l/editor.cpp, netbox/src/core/SessionData.cpp
Продолжаем бороться с сообщениями от valgrind.
Вот еще требует внимания:
```
==24529== Thread 7:
==24529== Source and destination overlap in memcpy(0x16673040, 0x16673040, 1280)
==24529==    at 0x4C32513: memcpy@@GLIBC_2.14 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24529==    by 0x46ACDE: memcpy (string3.h:53)
==24529==    by 0x46ACDE: swap_m(char*, char*, unsigned long, void*) (farrtl.cpp:1568)
==24529==    by 0x46BAAE: shortsort_m (farrtl.cpp:1532)
==24529==    by 0x46BAAE: qsort_m(void*, unsigned long, unsigned long, int (*)(void const*, void const*)) (farrtl.cpp:1291)
==24529==    by 0x176D7400: SetStartupInfo (MultiArc.cpp:40)
==24529==    by 0x557FDC: PluginA::SetStartupInfo(bool&) [clone .part.17] [clone .constprop.43] (PluginA.cpp:543)
==24529==    by 0x558068: …
```
=> fix some valgrind errors

README.md
There seems to be a bug in shields.io interface that produces cached badges, which is not what we want for public build status - https://github.com/badges/shields/issues/782
=> strip maxAge from status badge

far2l/filelist.cpp, far2l/filetype.cpp, far2l/filetype.hpp, far2l/usermenu.cpp
предлагаю выкинуть ExtractIfExistCommand(), т.к.
1. она не работает, всегда возвращает false, т.к. PrepareOSIfExist() пустая.
2. из-за этого не работают file associations.
3. т.к. командная строка целиком передаётся /bin/sh нет смысла проверять существование исполняемого файла; даже его отсутсвие это нормальная ситуация, исполняться может не файл а функция из ~/.bashrc
=> remove ExtractIfExistCommand()

WinPort/src/UI/Main.cpp
Костыль для ресайза окна на макоси. Как по нормальному пока не понятно, может просто более удачный wxWidgets взять, а не последний.
=> macos: fix window resize

far2l/copy.cpp, far2l/fileedit.cpp, far2l/pathmix.cpp, far2l/pathmix.hpp
в линуксе имена файлов могут содержать <, > и | 
кейс: редактор (F4) такие файлы не открывал; вьювер открывал.
=> remove ReservedFilenameSymbols

WinPort/src/UI/Main.cpp
Теперь фоновая загрузка 1%. Однако ректы все равно избыточные, а скрол в эдиторе тормозит.
=> macos: fix idle performance problem

multiarc/src/arccmd.cpp, multiarc/src/arcput.cpp
Multiarc has "%%R - Current archive folder" variable to specify destination archive sub-folder.  Unfortunately, it is always quoted, so combining it to form a path fails:
```
%%R/%%f
"fold name"/file name
```
This pull adds a new %%r variable (lowercase). It adds the current archive folder unquoted, and if the value is not empty, it appends a "/" - notice the quotes are added in the manually:
```
"%%r%%f"
"fold name/file name"
```
This allows adding to zpaq and probably other archives in sub folders.
=> Multiarc destination arc folder update

README.md
To avoid using IDE. Probably most users will just need to make binaries without opening the project in IDE.
=> Simplify README.md to use `make`

.gitignore, WinPort/src/UI/Main.cpp, WinPort/src/UI/wxWinTranslations.cpp, WinPort/src/UI/wxWinTranslations.h, utils/CMakeLists.txt, utils/include/INIReader.h, utils/include/ini.h, utils/src/INIReader.cpp, utils/src/ini.c
Здравствуйте!
The 32 RGB values are stored in ~/.config/far2l/palette.ini and may be
changed. Palette config is initialized with defaults if palette.ini is
absent in the directory. An error message is shown in the console if
an error occurs while parsing the .ini file.
Parsing is done with https://github.com/benhoyt/inih.
=> Add custom console RGB palette support

multiarc/src/MultiArc.cpp
Use `getcwd()` that's already used everywhere instead of glibc-specific `get_current_dir_name()`.
The latter exists on OS X/clang, but crashes.
=> Crash on OS X and streamline MakeFullName() implementation

farftp/src/HGet.cpp
From unlink man:
RETURN VALUE
Upon successful completion, these functions shall return 0. Otherwise, these functions shall return -1 and set errno to indicate the error. If -1 is returned, the named file shall not be changed.
=> Fix If logic

far2l/viewer.cpp
Можно было вообще без кастов CRSym оставить т.к. wchar_t gcc воспринимает как int, но пока пусть так побудет.
=> Fix some signed/unsigned comparisons warnings

far2l/tvar.cpp, inside/src/inside.cpp
По второму, где 0 на {} меняется: для полей-стуктур это ведь более корректная запись? Если по какой-либо причине не подходит, можешь отклонить, так то в коде много таких мест, это так сказать на пробу.
=> Cosmetic: remove some gcc wswitch warning

far2l/macro.cpp
Fixed crash on assigning already used keycode to recorded macro.
=> fixed pointer assignment after conversion to keycode

editorcomp/src/Editor.cpp
fix for https://github.com/elfmz/far2l/issues/342
Undo (ECTL_UNDOREDO) should be used instead of suggested characters removal (ECTL_DELETECHAR) when user cancels suggestion.
For proper operation suggestion is enclosed with EUR_BEGIN/EUR_END requests
=> fix for marking edited file dirty after cancelled autocomplete

editorcomp/src/Editor.cpp, far2l/copy.cpp
CmpFullNames() didn't use ConvertNameToFull() 
this caused CopyToSelf check to fail in case of copying files from current directory to itself, but with full path specification like this:
*.cpp  -> /full/path/to/current/dir/ 
So it was possible to mistakenly truncate all copied files to 0 
Proposed patch fixes this problem.
=> fix for CopyToSelf check

WinPort/src/APIRegistry.cpp, editorcomp/src/Editor.cpp
FindFile crashes when charset is set to Autodetect and there are one or more previously selected Favorite charsets in the list
This is caused by call to RegEnumValue() with lpData=NULL and lpcbData=NULL
According to MS specs https://docs.microsoft.com/en-us/windows/desktop/api/winreg/nf-winreg-regenumvaluea
The only invalid combination is valid lpData with lpcbData=NULL
Thre was no check for such condition in CommonQueryValue() called by RegEnumValue()
But the most significant are RegValueDeserializeXxx() functions where lpcbData is not checked for NULL value.
Patch adds error check in CommonQueryValue() and makes RegValueDeserializeXxx() functions safe against lpcbData=NULL condition.
=> Fix RegEnumValue() crash (affects FindFile)

editorcomp/src/Editor.cpp, far2l/copy.cpp, far2l/copy.hpp
Low speed was caused by too frequent progress bar updates
Refresh rate is limited to 1000ms (1 second) by default
It can be adjusted by ProgressUpdateThreshold registry value in System
=> fixed bug with slow copy (issue #490)

editorcomp/src/Editor.cpp, far2l/viewer.cpp
::Up() always uses byte offset, must be 16
::ReadString() uses byte count for 8/16-bit charsets, but word-count for 32-bit charset (checked by IsFullWideCodePage()). Must be 16 and adjusted for 32-bit charsets (those are not supported yet)
=> fix for Hex pgUp/Down offset missmatch issue #474

editorcomp/src/Editor.cpp, far2l/filestr.cpp
originally IsTextUnicode was used as the 1st test for unicode. 
Them return flags are checked if it is REALLY unicode.
Below we had UTF8 and euristic codepage checks
But due to wrong condition we never get to these check if IsTextUnicode reported that MY BY we have unicode check, regardless of further inspection on our side.
Actually we should continue with codepage checks if IsTextUnicode returns TRUE, but flag analysis tells that it doesn not.
=> fix for wrong detection files as Unicode

far2l/menubar.cpp
Wide string should be formatted with %ls specifier
For issue https://github.com/elfmz/far2l/issues/491
=> Fix empty menu bar in "Always show menu bar" mode

cmake/modules/FindLibNEON.cmake, cmake/modules/FindLibNfs.cmake
>>try branch https://github.com/elfmz/far2l/tree/fix-some-includes
>make result:
>/usr/local/include/nfsc/libnfs-raw-nfs.h:37:10: fatal error: 'nfsc/libnfs-zdr.h' file not found
this is another way (modify cmake configs, not sources)
make result:
[100%] Built target far2l
Far Manager, version 2.2 (build 19/06/10-7f13718-alpha) Darwin x86_64
=> fix compile errors (neon, nfsc)

far2l/main.cpp
Allows to run `far2l //bin //etc` to open `/bin` and `/etc` in two panels. Originally they were treated as flags (`/B` and `/E`) instead of pathes. Double slash is used to distinguish flags and UNIX path.
=> Add ability to specify initial path for panels from command line

README.md
I use Far Manager successfully on Debian using the same instructions as on Ubuntu, so I added Debian to the documentation to reflect this.
Also added an archival link for CodeLite because the active link http://codelite.org/LiteEditor/WorkingWithCMake is no longer working and I couldn't find it on the current web site.
=> Updated "Ubuntu" to "Debian/Ubuntu" and addressed a broken link

far2l/RegExp.cpp
...at the beginning of a line.
Very stable on Mac, just search for a regex starting with`\b`.
=> Crash in regex engine searching for a word boundary 

CMakeLists.txt
In the latest toolchain LibArchive is included, so even if brew has own version of LibArchive, the version from SDK is used causing build errors. Need to set library location explicitly.
=> Fix detection of LibArchive library on MacOS

colorer/src/shared/common/Logging.cpp
Colorer uses global variable "log" which interferes with globals in standard library (in math.h)
It causes build to fail (Xcode 12.0.1)
=> Fix colorer plugin build in MacOS

far2l/bootstrap/scripts/farlang.templ.m4, far2l/config.cpp, far2l/config.hpp, far2l/vtshell.cpp
User can select the shell he prefer to use in FAR2L.
=> Allow shell to be overriden in "Command line settings"

WinPort/src/Backend/TTY/TTYInputSequenceParser.cpp, WinPort/src/Backend/TTY/TTYInputSequenceParser.h
In TTY mode it is not possible to use numeric keys with modifiers (Ctrl/Shift/Alt) because there are no special ANSI codes are sent by terminals. 
Some shortcuts in FAR depend on these keys, e.g. folder shortcuts, and it's not possible to make them work in TTY.
I introduced support of virtual escape sequences form ESC+[50;M~ to ESC+[59;M~ which could be bound to numeric keys in terminal. 
See https://gist.github.com/anteo/864c72f64c2e7863353d909bf076aed7 for custom key mapping for iTerm2.
I personally actively used it in my fork.
If this fix is appropriate, it makes sense to write a note in README.md as well.
=> Add virtual escape sequences for numeric keys to support Ctrl/Shift/Alt+0...9 keys in TTY (needs additional setup in terminal settings);

far2l/CMakeLists.txt
I noticed that when I change WinPort library sources, main executable is not rebuilt automatically.
I added dependency on libWinPort.a, so when library object file is changed, main executable is also rebuilt.
=> Fix the issue when FAR2L is not rebuilt automatically when WinPort sources are changed

multiarc/src/arccmd.cpp
Workaround for problem with multiarc and .zip archives generated by Google Forms. See https://github.com/elfmz/far2l/issues/753
=> Multiarc utf8 workaround

multiarc/src/MultiArc.cpp, multiarc/src/MultiArc.hpp, multiarc/src/arccmd.cpp, multiarc/src/formats/zip/zip.cpp
It's better to select code page for OEM .zip archives based on system locale instead of always using code page 866.
That is exectly how Windows internal "zip folders" tool works. Locale-to-CP translation table taken from Wine sources.
See https://github.com/elfmz/far2l/issues/753 for details
=> Smarter processing of non-latin filenames inside .zip archives

CMakeLists.txt
My previous fix wasn't checked well and led to LibArchive completely not used on MacOS.
This is corrected and verified version.
=> Fix libarchive detection on MacOS

WinPort/src/Backend/TTY/TTYInputSequenceParser.cpp
One more addition to support Ctrl/Shift/Alt+Enter keys in TTY mode
Ctrl/Shift+Enter keys doesn't have any special ANSI sequence, but Ctrl+Enter is used e.g. to copy selected file name to command line, so it's very useful to have it in TTY.
Alt+Enter has its own code (0x1b 0x0d), which is sent by terminal by default, so I've added its support too.
Here are  iTerm2 key mappings (xterm-compatible) for FAR2L:
https://gist.github.com/anteo/864c72f64c2e7863353d909bf076aed7
=> Add virtual escape sequences for Enter key to support Ctrl/Shift/Alt+Enter keys in TTY (needs additional setup in terminal settings);

multiarc/src/arccmd.cpp
This is related to work you guys did recently.
Unzip in MacOS doesn't have -I or -O options, so extracting ANY files just doesn't work.
I have no idea how it could be solved without -I and -O, so let's skip new logic for MacOS (as a quick workaround)
=> Workaround for Unzip to work in MacOS (skips recent OEM encoding checks for now)

far2l/filelist.cpp
В диалоге параметров сортировки файлов (по Ctrl-F12) по клавише "-" на "Use case sensitive sort" меняется значение у параметра "Numeric sort".
=> CtrlF12 dlg fix (save the wrong collation)

WinPort/src/Backend/WX/wxMain.cpp
Got the sucker! It was caused by the #4 workaround.
=> #325: Arrow repeated arrow keystroke was ignored at random on MacOS.

WinPort/src/Backend/WX/wxMain.cpp
=> Work around Enter not working after Alt-letter quicksearch on Mac.

NetRocks/src/Op/OpExecute.cpp, WinPort/src/Backend/TTY/TTYBackend.cpp, WinPort/src/Backend/TTY/TTYOutput.cpp, WinPort/src/Backend/TTY/TTYOutput.h, WinPort/src/Backend/WinPortMain.cpp, far2l/AnsiEsc.cpp, far2l/AnsiEsc.hpp, utils/include/TTYRawMode.h, utils/src/TTYRawMode.cpp
Measurements:
terminal1: socat -v TCP-LISTEN:2222,fork TCP:127.0.0.1:22 2>ssh.log 
terminal2: ssh -p 2222 127.0.0.1
terminal2: ...password...
terminal2: far2l
terminal2: Ctrl+O 6 times (3 times hide/show panels)
terminal2: F10
terminal2: exit
terminal1: Ctrl+C
terminal1: du -bs ssh.log
Results shown twice traffic reduction:
old far2l: log size ~80KB
new far2l: log size ~40KB
also to compare, same test with mc instead of far2l produces ~70KB log size.
=> TTY backend traffic optimization

far2l/filelist.cpp, far2l/filelist.hpp
Added Cmd/Ctrl-C shortcut to copy current command or file(s), and Alt-Shift-C to copy full path(s).
Not sure this is all that needs to be done, please consider this WIP.
* Is there a plan to resurrect copying files for Explorer/Finder?
* This probably needs to be documented?
* Do we care for UNC paths?
=> #909: Copy to clipboard the full path or short name of a current file on small keyboards.

far2l/Mounts.cpp, far2l/bootstrap/mounts.sh
- allow for an optional user script `~/.config/far2l/mounts.sh`
- this is similar to other scripts (open.sh, etc.)
- also allows for complete customization of drive select menu (see example below)
- only add shortcut for rootfs (`/`) if the shortcut is not already set
example of mounts.sh:
```
exec \
cat << EOF
/run/media/$USER	&M
$HOME	&H
/	&/
EOF
```
note the `exec` which allows to skip other code from standard `mounts.sh`
=> improvements for mounts.sh

far2l/pathmix.cpp
Fixes an issue on FreeBSD (and maybe other systems) where if argv[0] was a relative path, g_strFarModuleName would be missing a directory slash, resulting in far2l failing to find its language data.
=> add forward slash

far2l/bootstrap/mounts.sh
before
```
$ dfcmd='df -T | awk "-F " '\''{n=NF; while (n>5 && ! ($n ~ "/")) n--; for (;n<NF;n++) printf "%s ", $n; print $n "\t" $2 }'\' ; eval "$dfcmd" ;
Available Use% Mounted on	Type
/	ext4
/dev	devtmpfs
```
after
```
$ dfcmd='df -T -m | awk "-F " '\''{n=NF; while (n>5 && ! ($n ~ "/")) n--; for (;n<NF;n++) printf "%s ", $n; printf "%s\t%5s/%5sM %8s", $n, $5, $3, $2; print "" }'\' ; eval "$dfcmd" ;
Available Use% Mounted on	Available/1M-blocksM     Type
/	 2637/ 9816M     ext4
/dev	  445/  445M devtmpfs
```
=> update mounts.sh to include free / total usage

far2l/bootstrap/CMakeLists.txt, far2l/bootstrap/kblayouts.ini, far2l/src/filelist.cpp, far2l/src/filelist.hpp, far2l/src/global.cpp, far2l/src/global.hpp, far2l/src/main.cpp, far2l/src/panel.cpp, far2l/src/panel.hpp
Solution for #780. Adopted for current master
Layout[s] translation table[s] configurable via .ini file, locale-dependent
=> Trying different keyboard layout[s] on FastFind fail

multiarc/configs/plug/custom.ini
Allow browsing QEMU disk images (QCOW2).
Not too helpful, because allows extracting only disk partitions as *.img, but better than nothing.
=> ma: support QCOW2 format

WinPort/src/Backend/WX/CMakeLists.txt, WinPort/src/Backend/WX/wxMain.cpp
Even more compact version of previous fixes. Enables support for Alt+NonLatinLetter KeyUp/KeyDown handling not only on wx 3.1.3, but also on other versions in which it is available.
This is just Alt+non_latin fix, without fixes for Ctrl+non_latin (like Ctrl+`ю`)
=> Fix for Alt+NonLatinLatters on wx3.0 — minimal changes

far2l/src/main.cpp
allows things like "far2ledit -an file.txt"
=> use last command line parameter, not first

far2l/src/vt/vtshell_translation.cpp
updated vt translations to mimic GNOME Terminal's escape seqs
=> fixes #1241: wrong escape codes for arrow keys

far2l/src/locale/DetectCodepage.cpp
In Ubuntu 22.04 uchardet returns IBM852 on some source code files with pseudographic chars in comments. While not being perfect (it should be CP437), this guess is far better then WINDOWS-1252 (as in Ubuntu 20.04 on the same files) or UTF-8 (as if far2l do not understand uchardet return string).
This PR fixes far2l's understanding of uchardet return values like this.
=> better charset detection

far2l/src/plug/plugins.cpp
Если плагин вызван из меню плагинов, и плагин вызовет `ActlKeyMacro( MCMD_GETAREA )`, то он получит `MACROAREA_MENU`, независимо от реальной макрообласти.
В своё время это починили в Фар3. Предлагаю фикс для Far2l.
=> Fix incorrect return of MCMD_GETAREA

far2l/src/plug/plugins.cpp
1. Данное изменение позволяет назначать не-латинские хоткеи в меню плагинов и конфигурации плагинов.
2. Также устраняется возможный крэш при наличии плагинов, экспортирующих `ProcessDialogEvent`, поскольку им передавалась строка (хоткей), которая не была валидной `wchar_t*`. (Могу продемонстрировать  этот крэш в непатченой версии).
=> Fix assigning hotkeys in plugins and config menus

far2l/src/plug/wrap.cpp
Это фикс для #1267, но не начального крэша, а того, который описан внизу #1267  (GitHub не позволил мне переоткрыть этот issue).
ANSI-плагины используют ту же функцию `DefDlgProc`, что и юникодные плагины.
Но в сообщениях `DN_DRAWDLGITEM` и `DN_EDITCHANGE` Param2 является указателем на DialogItem, в результате `DefDlgProc` получает указатель на DialogItem, в котором Data - это `char*`, а не `wchar_t*`.
Сама функция `DefDlgProc` ничего не делает с этим указателем, но если есть плагин, обрабатывающий `ProcessDialogEvent`, то функция `DefDlgProc` вызывает этот `ProcessDialogEvent`, передаёт ему ANSI DialogItem, и далее может произойти крэш, ибо плагин такой засады не ожидает.
=> Fix crash with ANSI plugins that call DefDlgProc

far2l/src/fileedit.cpp
Это фикс для #1287.
При вызове `EditorControl(ECTL_SAVEFILE)`, если передана невалидная кодовая страница, возвращает `FALSE`.
В отсутствие данного фикса возвращается `TRUE`, а файл сохраняется пустым (ноль байт).
=> Fix ECTL_SAVEFILE with invalid code page (see #1287)

far2l/src/mix/panelmix.cpp
При открытии панели плагина, содержащего кастомные колонки, код ширины которых "0", всё было нормально, пока количество колонок было < 10. Если колонок было 10, то вместо равномерного распределения ширин, первые 9 были шириной в 1 символ, а последняя занимала всё остальное место.
Не вдаваясь в детали механизма бага - его суть в том, что массив `ColumnTypeWidth[]` был на один элемент короче массива `ColumnSymbol[]`.
=> Fix the C9 custom column

far2l/src/help.cpp
Некорректная обработка `.Options CtrlStartPosChar` приводила к искажениям отображаемого текста, причём эти искажения изменялись при изменении размеров окна справки. Вот пример этих искажений:
=> Fix text corruption in displaying help files

NetRocks/src/Protocol/FTP/FTPParseMLST.cpp, far2l/src/base/SafeMMap.cpp, far2l/src/vt/vtcompletor.cpp
This simple PR fixes `error: ‘time’ was not declared in this scope` compilation errors with recent versions of gcc/clang/glibc.
=> Compilation fix with recent gcc/clang versions

WinPort/src/Backend/WX/wxMain.cpp, WinPort/src/Backend/WX/wxMain.h
- first commit uses wxDefaultPosition for WinState::pos
to allow window manger to select startup position if winstate file contains -1 for x/y positions
(always using fixed position is not always desirable)
- second commit restores functionality to set windows size in characters if consolesize file is present
(i use same config for size of windows in chars across different machines,
and size in pixel is not good enough, also because it is difficult to resize window to get rid of black padding
if size is not multiple of chars) 
possible modification (if requested):
- move consolesize values to winstate (but consolesize was already present in past versions)
=> allow WM to select window position, and restore possibility to set window size in chars

.editorconfig, NetRocks/.editorconfig, SimpleIndent/.editorconfig, align/.editorconfig, autowrap/.editorconfig, calc/.editorconfig, colorer/.editorconfig, compare/.editorconfig, drawline/.editorconfig, editcase/.editorconfig, editorcomp/.editorconfig, far2l/.editorconfig, farftp/.editorconfig, filecase/.editorconfig, incsrch/.editorconfig, inside/.editorconfig, multiarc/.editorconfig, multiarc/src/formats/7z/7z.cpp, multiarc/src/formats/custom/custom.cpp, multiarc/src/formats/rar/rarmainstub.cpp, python/.editorconfig, tmppanel/.editorconfig
It's default styling is 2 spaces, so let's make exclusions only for ha sources (as it is imported code) and libarchive wrapper (as it is written from scratch).
=> Make indentation more consistent throughtout MA; misc .editorconfig fixes

WinPort/src/Backend/WX/wxMain.cpp, WinPort/src/Backend/WX/wxWinTranslations.cpp
The previous attempt to detect key_code could behave incorrectly if the system has Latin keyboard layouts other than English. For example, on the German keyboard layout, the keys like `;` or `'` are placed differently from English one, also do `z` and `y` keys.
So I modified the code so that the detection of key_code will only work if the system has English keyboard layout installed, and only English keyboard layout would be used for detection.
Better approach would be to use xkbcommon lib (as it allows to do key mapping using keyboard layouts not enabled system wide; [example](https://github.com/wxWidgets/wxWidgets/issues/23379#issuecomment-1488563133)), but it is one more dependency so we probably do not want it.
=> Better key_code detection

WinPort/src/Backend/TTY/TTYX/TTYX.cpp
`X11/XKBlib.h` is part of x11-dev, so can be safely moved out of `#ifdef TTYXI`
=> fix ttyxi module headers

far2l/CMakeLists.txt, far2l/bootstrap/CMakeLists.txt, far2l/bootstrap/scripts/farlng.pl, far2l/src/console/constitle.cpp, far2l/src/ctrlobj.cpp, far2l/src/farversion.h, far2l/src/global.cpp, far2l/src/global.hpp, far2l/src/plug/PluginA.cpp, far2l/src/plug/PluginW.cpp, far2l/src/plug/plugapi.cpp, far2l/src/plug/plugins.cpp
see https://github.com/elfmz/far2l/issues/1515#issuecomment-1451851021
NB! Copyright string was encoded using XOR since at least version 1.64 (see ctrlobj.cpp [in 1.64](https://github.com/FarGroup/FarManager/releases/tag/release%2F1.64)). Probably the reason was to prevent from removing or changing copyright string in binary file. We probably do not need such protection currently, so I do not reproduced it in new copyright string generation method.
=> No redundant recompile on git revision change any more

CMakeLists.txt, python/CMakeLists.txt, python/configs/plug/plugins/uadb.py, python/src/prebuild.sh, python/src/python.cpp
new cmake parameters:
VIRTUAL_PYTHON=-DVIRTUAL_PYTHON=/devel/bin/python3/bin/python
VIRTUAL_PYTHON_VERSION=-DVIRTUAL_PYTHON_VERSION=3.8
VIRTUAL_PYTHON - which python interpreter use
VIRTUAL_PYTHON_VERSION - which python version to use when finding the python environment configuration in cmake, the version must match the version of the indicated interpreter in the previous variable
version is specified as major.minor form, ie. for python 3.8.10 it's 3.8
=> python in virtual env

python/configs/plug/far2l/pluginmanager.py, python/configs/plug/plugins/uadb.py
probably the most common problem with this plugin - pointers used after exiting the python procedure
self.s2f returns a pointer to the buffer that must survive the exit from python to far2l, hence the need to hold such a buffer in the variables assigned to self
=> python and pointers

far2l/bootstrap/view.sh, far2l/src/setattr.cpp
For obtaining file info in BriefInfo():
for file '-a.txt' command
`file -a.txt`
give invalid option error, but
`file -- -a.txt`
will work correctly
For view.sh:
Unfortunately
tar, chafa, jp2a, ctags
did not understand `--` as end of parameters.
All others understand `--` (tested on Ubuntu 22.04).
=> Correction obtaining file info for filenames starting with a dash '-'

python/src/prebuild.sh
There may be a problem with starting the plugin: https://stackoverflow.com/questions/62658237/it-seems-that-the-version-of-the-libffi-library-seen-at-runtime-is-different-fro
on debian based systems another package is needed:
apt install libffi-dev
=> cffi from pypi is outdated, fresh compile is needed

far2l/src/help.cpp
Additional hardcore English notification for users that now some help topics may contain incorrect legacy info.
=> Help: hardcore bottom notification about BETA & windows legacy

far2l/src/cfg/config.cpp, far2l/src/dialog.cpp
1) Was "=== Title===", now "=== Title ==="
2) Copy "Save commands history" to "System settings" config dialog.
Now all "Save commands history", "Save folders history" & "Save view and edit history"
can be easily found together one place.
=> Space in dialog windows after title before border line & All Save history config in one place

far2l/src/main.cpp
Unification `far2ledit` & `far2l -e` for edit new empty file (idea from #1710)
Now far2l code use `Msg::NewFileName` for new filename
and, if in current directory file has this name, it will be open :(
May be in future depricate use names `Msg::NewFileName` and use `""` for new filename?
But it required at least refactor `fileedit.cpp`: `const wchar_t *Name` in function `FileEditor::Init(`
and `filelist.cpp`: `do`...`while (strFileName.IsEmpty());`
=> Unification far2ledit & far2l -e for edit new empty file

far2l/bootstrap/scripts/FarEng.hlf.m4, far2l/src/filetype.cpp, far2l/src/filetype.hpp, far2l/src/panels/filelist.cpp, far2l/src/setattr.cpp
1) **History commands by Alt-F8: fix save directory from panel by Enter**
Fix for #1618
2)  **Attributes dialog: Owner and Group Small Fix**
Fix after #1717
Some `/etc/passwd` and `/etc/group`
contain comments starting with '#'
and now fix to skip it.
Also skip lines witout ':'.
Now direct reading from `/etc/passwd` or `/etc/group`
May be rewrite to obtain by `getpwent()` & `getgrent()` ?
3)  **Help typo fix**
=> 1) History commands by Alt-F8: fix save directory from panel by Enter & 2) Owner and Group Small Fix

far2l/src/vmenu.cpp
=> VMenu Title During Filtering - hide vmenu title only if (menu title + filter text) is wider than window

far2l/src/setattr.cpp
Improvements after #1690 & 65e1870 & 93a50b2
* SA_TXTBTN_INFO & SA_EDIT_INFO fields now never hidden (when seleceted >1 it shows the number of selected files + directories)
* SA_EDIT_INFO not readonly only if symlink
* If symlink then let's first focus not on the editable SA_EDIT_INFO, but on the button SA_TXTBTN_INFO
=> Set Attributes Dialog: Improvements

far2l/src/setattr.cpp
Now confirmation texts are draft, it will need to be written more accurately.
=> Set Attributes Dialog: add draft confirmation if new symlink target not exist

far2l/bootstrap/scripts/FarRus.hlf.m4
Продолжение #1748, #1750 и 1753
в macOS в wezterm поддержка режима kitty не работает
=> Help: Особенности FAR2L - начало работы - корректировка

multiarc/src/formats/7z/C/AesOpt.c
Fixed in GCC 4.8+ or some later version. Checked on COS7, GCC 4.8.5.
Details in sevenzin discussion:
https://sourceforge.net/p/sevenzip/discussion/45798/thread/0d673fcfaa/
=> fix __AES__ for old GCC

README.md
1) On some systems (like Ubuntu 14.04 LXC image) you need to install pkg-config manually for cmake to succeed.
2) All cmake options needed to build far2l without any dependency are now documented in README.
=> minor readme improvements

CMakeLists.txt
@m32
Update CMakeLists.txt to fix python plugin.   
Some key python plugin files copied to wrong destination by install procedures. Fix it by changing  "share" to "lib".
Without this fix command "py:load" says "py:load: command not found"
=> Update CMakeLists.txt to fix python plugin

far2l/src/cmdline.cpp, far2l/src/cmdline.hpp
Draft `far:about` a la far3, but not identical (not in terminal, in list with details)
Думал повторить как в far3, но не разобрался как в far2l делать вывод в терминал и сделал через окно списка.
В окне списка возможно стоит пофиксить эффект, что при наличии LIF_SEPARATOR и прокрутки ниже первой страницы экрана в заголовок списка добавляется ` -` - в истории это к месту, а тут не мешающая некрасивость.
=> Command prefix `far:` and draft `far:about` command

far2l/src/cfg/ConfigSaveLoad.cpp, far2l/src/cfg/ConfigSaveLoad.hpp, far2l/src/cmdline.cpp
new draft `far:config`: without editable
update draft `far:about`: expanded plugins information + refactoring
---
@elfmz правильно ли я понял, что в **far:about** реализованном через VMenu, нормально не запретить по щелчку мыши делать ENTER, в результате чего и закрывается VMenu?
Поставить для каждого элемента `Flags = LIF_GRAYED` не вариант - цвет сразу становится плохим 😿
`ReadInput` возвращает только клавиши, а тут `ProcessMouse` гонит преобразование уже внутри VMenu без его перехвата наружу.
Установка `ListAbout.SetFlags(VMENU_MOUSEDOWN);` или удаление `ListAbout.ClearFlags(VMENU_MOUSEDOWN);` также не такое поведение мыши не повлияло.
---
В **far:config** при включенном фильтре Ctrl-Alt-F пересоздание списка по Ctrl-H или Ctrl-A сбивает фильтрацию.
Вроде не увидел как проверить …
=> new draft `far:config` & update draft `far:about`

python/src/python.cpp, python/src/pythongen.py
changes allowing the use of python >= 3.9
PyErr_Print belongs to the API and cannot be called after PyGILState_Release
resolves #1818
=> python >= 3.9

far2l/src/cfg/ConfigSaveLoad.cpp, far2l/src/cmdline.cpp, far2l/src/vmenu.cpp, far2l/src/vmenu.hpp
* vmenu: - new Flag VMENU_BYSINGLEMOUSECLICK_ONLYSELECT not produce ENTER (usefull when VMENU_MOUSEREACTION clear) - by DOUBLE_CLICK always produce ENTER
* `far:about` & `far:config` use VMENU_BYSINGLEMOUSECLICK_ONLYSELECT
=> New Flag VMENU_BYSINGLEMOUSECLICK_ONLYSELECT

.clang-format, .clang-format.json
.clang-format updated to the current syntax according to the [ClangFormatStyleOptions](https://clang.llvm.org/docs/ClangFormatStyleOptions.html )
additionally schema overrides for CLion added as .clang-format.json to reflect changes from https://github.com/elfmz/llvm-project repo
=> clang-format update and schema overrides

NetRocks/src/Protocol/SHELL/Parse.h, NetRocks/src/UI/Settings/ConfigureProtocolSHELL.cpp
Fix for  NetRocks-SHELL fail to build due to missing include <cstdint>
=> Fix for issue #1873

far2l/src/filefilterparams.cpp, far2l/src/setattr.cpp
fix:
FmtMask1 = L"99%c99%c99%c99N"
FmtMask2 = L"99%c99%c9999N"
and
FmtMask3 = L"N9999%c99%c99";
without this in Attributes dialog (Ctrl+A)
field year contains 5 digits number instead of  1 space and 4 digits. 
And because of this displayed date it's not correct, 
date "2023/10/13"
is displayed as "20231/01/3 "
fix: filefilterparams.cpp
function bool FileFilterConfig(FileFilterParams *FF, bool ColorConfig)
// ...
switch (DateFormat) {
// ...
strDateMask.Format(L"99%c99%c9999N", DateSeparator, DateSeparator);
// ...
strDateMask.Format(L"99%c99%c9999N", DateSeparator, DateSeparator);
// ...
strDateMask.Format(L"N9999%c99%c99", DateSeparator, DateSeparator);
// ...
}
// ...
strTimeMask.Format(L"99%c99%c99%c99N", TimeSeparator, TimeSeparator, DecimalSeparator);
// ...
=> Update setattr.cpp and filefilterparams.cpp

far2l/bootstrap/scripts/farlang.templ.m4, far2l/src/delete.cpp
* При удалении симлинка на файл или на каталог удаляется именно симлинк - это логично.
Используя существующие DeleteLinkTitle, AskDeleteLink, AskDeleteLinkFolder и AskDeleteLinkFile
сделал, чтобы текст диалогового окна отличался от удаления обычного файла/каталога
хотя бы при удалении единичного symlink на файла/каталог.
* Alt+Del для symlink на файл без предупреждений вытирал содержимое исходного файла,
поправил аналогично предупреждению для hardink,
но возможно стоит такие предупреждения разнести,
чтобы [All] & [Skip all] не разрешали общее поведение (???).
* Alt+Del для symlink на каталог вообще нормально не работал и портил имя симлинка
- убрал безоговорочно wipe для каталогов из symlink,
но не проверял досконально на вложенных каталогах и ссылках.
* Вопрос 1 (???) Удаление symlink в …
=> delete.cpp: correct messages and behavior during deleting symbolic links

far2l/src/cfg/ConfigSaveLoad.cpp
Задумываюсь как бы перетянуть в far:config полезный в far3 вызов по **Shift-F1** относящегося к текущему параметру раздела помощи. Похоже для этого придётся расширять класс `class OptSerializer` хранением `const wchar_t *HelpTopic` или `FARString *HelpTopic`? Вопрос - нет ли каких то противоречий расширению класса `class OptSerializer` и какой вариант лучше кодить?
=> far:config - Edit input also hex values & Rearrange all NSecSystem together

NetRocks/src/Protocol/SHELL/Helpers/ways.ini
Add missing ssh port in ways.ini. 
Without this fix NetRocks Shell protocol ignores connection port in configuration and unable to connect to nonstandard port.
=> Add missing ssh port in ways.ini

far2l/src/panels/flupdate.cpp
How to reproduce
- build Far2l with option -DCMAKE_CXX_FLAGS =-D_GLIBCXX_ASSERTIONS
- Run Far2l, open Plugins - Temporary panel
- or Run Far2l, open any archive with empty folder
=> bugfix: Far2l process crash if compiled with -D_GLIBCXX_ASSERTIONS

WinPort/windows.h
One of plugins, which I'm porting, [uses it](https://github.com/atsidaev/far2l-plugins-speccy/blob/9c3b4593490903020af68e7d3343a06ddacafafc/xISD/manager_get_files.cpp#L88).
The function itself exists but it is only visible as WINPORT_SetFileTime.
=> Add SetFileTime to the functions, which are exported with WINPORT_DIRECT

far2l/src/FilesSuggestor.cpp, far2l/src/FilesSuggestor.hpp, far2l/src/edit.cpp, far2l/src/mix/panelmix.cpp, far2l/src/mix/panelmix.hpp, far2l/src/mix/strmix.cpp, far2l/src/mix/strmix.hpp
Закрывает #2071 и #1670
Не уверен, что во втором коммите в FilesSuggestor.cpp реализовал наиболее эффективно убирание экранирования, ибо сначала оно там излишне многократно делается, но решил не ковырять эту логику, а наиболее минимально влезать в действующий код.
=> Force non escaping

WinPort/src/Backend/TTY/TTYInput.cpp, WinPort/src/Backend/TTY/TTYInputSequenceParser.cpp, WinPort/src/Backend/TTY/TTYInputSequenceParser.h, WinPort/src/Backend/TTY/TTYInputSequenceParserExts.cpp, WinPort/src/Backend/TTY/TTYOutput.cpp
fixes #2072 
Here is complite fix for double encoded mouse sequences in win32-input-mode under WSL.
Due to bug in events encoding in windows ConPTY, mouse input not only encoded in X10 mouse sequences but characters in it also encoded again as win32-input-mode sequences. I patch up this by adding separate buffer for for accumulate unpacked chracters and then parsing it sepparatly.
In addition, I wrote some annotations to describe the process..
All tested under windows 11 WSL Ubuntu 22.04. Seems works just fine.
=> Work-around for win32-input-mode mouse sequences and SGR extended mouse report

WinPort/src/Backend/WX/wxClipboardBackend.cpp
Fix after #2053 & https://github.com/elfmz/far2l/commit/ca3ccdcac00f5c6d6228596ec9aa5f255a9cc8ec
In my x11 before this fix pasting in Telegram with last strange char:
after fix all correct:
Please anybody verify in Wayland and in WSL.
=> Fix copy to Telegram last NUL char

far2l/src/fileedit.cpp
Before fix during save file with AttrStr chars was added to str
=> Fix editor AttrStr symbols duplicate during save file

far2l/src/filestr.cpp, far2l/src/locale/DetectCodepage.cpp
1. https://github.com/elfmz/far2l/issues/2075
задействует uchardet
2. https://github.com/elfmz/far2l/issues/2076
позволяет корректно распознавать UTF-32 (взято решение от https://github.com/shmuz/far2m/commit/3f453c4505a88bdc3e5412a89c7e06ca33a388fe )
3. https://github.com/elfmz/far2l/issues/2078
апдейт актуальных строковых констант, возвращаемых uchardet
=> bugfixes and improvements in automatic encoding detection

WinPort/src/Backend/WinPortMain.cpp
Fix build under Ubuntu 18.04 
```
../../WinPort/src/Backend/WinPortMain.cpp:39:10: fatal error: filesystem: No such file or directory
#include <filesystem>
^~~~~~~~~~~~
compilation terminated.
```
- remove  unnecessary includes from WinPortMain.cpp
=> Fix build under Ubuntu 18.04 - update WinPortMain.cpp

far2l/src/execute.cpp
fix #2067 -- **вариант** решения № 2
<details><summary>Суть проблемы:</summary>
Когда [ExecClassifier](https://github.com/elfmz/far2l/blob/0ee8118739d4763d28777cd6de4c6208a58c66e8/far2l/src/execute.cpp#L77) сталкивается с битой или недоступной символической ссылкой, он возвращает управление, не взведя в true [флаги](https://github.com/elfmz/far2l/blob/0ee8118739d4763d28777cd6de4c6208a58c66e8/far2l/src/execute.cpp#L93) _dir или _file.
Далее, в функции [ExecuteA](https://github.com/elfmz/far2l/blob/0ee8118739d4763d28777cd6de4c6208a58c66e8/far2l/src/execute.cpp#L374) проверки [ec.IsDir()](https://github.com/elfmz/far2l/blob/0ee8118739d4763d28777cd6de4c6208a58c66e8/far2l/src/execute.cpp#L387) и [ec.IsFile()](https://github.com/elfmz/far2l/blob/0ee8118739d4763d28777cd6de4c6208a58c66e8/far2l/src …
=> fix #2067, option 2: unneeded open.sh call after clicking on a broken symbolic link

WinPort/src/Backend/Backend.h, WinPort/src/Backend/TTY/TTYBackend.cpp, WinPort/src/Backend/TTY/TTYBackend.h, WinPort/src/Backend/WinPortMain.cpp
fix #2139:
Method ArgOptions::ParseArg() [used](https://github.com/elfmz/far2l/blob/e6ad61a1ebfd816232f24bf5e224bf7ef83c2ebc/WinPort/src/Backend/WinPortMain.cpp#L288) internal buffer of [str](https://github.com/elfmz/far2l/blob/e6ad61a1ebfd816232f24bf5e224bf7ef83c2ebc/WinPort/src/Backend/WinPortMain.cpp#L349) (**local** std::string) [passed](https://github.com/elfmz/far2l/blob/e6ad61a1ebfd816232f24bf5e224bf7ef83c2ebc/WinPort/src/Backend/WinPortMain.cpp#L355) from WinPortMain(), this led to the corruption of the variable value.
Type of nodetect variable  was changed from char* to DWORD, and now it is used as a bitmask.
=> fix #2139: type of nodetect variable changed from char* to dword (now used as bitmask)

far2l/src/filestr.cpp, far2l/src/locale/DetectCodepage.cpp
1) treat uchardet's ASCII as UTF-8
2) replaced spaces with tabs according to CODESTYLE.md
=> uchardet: 1) treat ASCII as UTF-8; 2) indentation fixes

far2l/src/ctrlobj.cpp
fix #2142: restore positioning on files in panels in case of manual setup saving (Shift-F9) too
=> fix #2142: restore positioning on files in panels in case of manual setup saving (Shift-F9) too

far2l/src/delete.cpp
[RemoveToRecycleBin](https://github.com/elfmz/far2l/blob/47a5092dbeb29a07095a7a563ad0410a922ea536/far2l/src/delete.cpp#L716) function [checks](https://github.com/elfmz/far2l/blob/47a5092dbeb29a07095a7a563ad0410a922ea536/far2l/src/delete.cpp#L727) if privilege elevation is necessary based on the full filename passed to it.
However, the ability to delete a file is determined by permissions on the directory containing the file, not on the file itself.
Thus the following troublesome situations may arise:
1. Unnecessary sudo prompt when deleting _**a file we do not own**_ from _**a directory we do own**_. Moreover, the subsequent moving to trash will be done as root, so the deleted file will end up in `/root/.local/share/Trash/` instead of `/home/<username>/.local/share/Trash/`.
2. The sudo …
=> Fix sudo privilege elevation for files moving to trash

utils/src/LocalSocket.cpp, utils/src/PipeIPC.cpp
After applying the commit https://github.com/elfmz/far2l/commit/85d1dc8c2d232e98e26ad9094509dd5590f5a6e7, it became necessary to use gcc > 8
If you install and use gcc12:
sudo pkg install gcc-12_5
export CC=/usr/local/bin/gcc; export CXX=/usr/local/bin/g++
cmake -DUSEWX=yes -DCMAKE_BUILD_TYPE=Release -G Ninja ..
cmake --build .
You will get new errors:
FAILED: utils/CMakeFiles/utils.dir/src/LocalSocket.cpp.o /home/user/src/far2l-staging/utils/src/LocalSocket.cpp:197:21: error: 'select' was not declared in this scope; did you mean 'exect'?
197 |                 if (select(maxfd + 1, &fdr, (fd_set*)nullptr, &fde, (timeval*)nullptr) == -1) {
|                     ^~~~~~
|                     exect
=> Fix build on DragonflyBSD 6.4. with gcc12

far2l/bootstrap/open.sh, far2l/bootstrap/ps.sh
1. Use `{ ..; }` instead of `(..)` and remove superfluous `(..)` around condition to avoid subshell overhead.
2. Replace `$'..'` with `$(printf '..')` for better posix shell compatibility.
3. Replace `test` with `[ .. ]` for better readability.
4. Add `read -r` option to handle backslash key presses too.
<hr>
Отдельный вопрос по поводу вот [этой](https://github.com/elfmz/far2l/blob/cafa42faf1f37e358ed241d98bd0d085574b220b/far2l/bootstrap/ps.sh#L24) конструкции в ps.sh:
```sh
read -n 1 k <&1
```
Переменная `k` и перенаправление `<&1` из stdout несут какой-то сакральный смысл, или это артефакты, которые можно удалить?
=> open.sh and ps.sh scripts corrections

.vscode/launch.json, .vscode/settings.json
Add basic support for build and debug with Visual Studio Code .
Install free Visual Studio Code. 
Install CMake Tools extension.
Change directory to cloned far2l git .
Run:
code .
=> Add basic support for build and debug with Visual Studio Code .

multiarc/src/arccmd.cpp
Одно из условий потерялось, обнаружилось при тестировании фикса с пересозданием /dev/null из-под root'а, вернул на место.
=> multiarc: check if we have read access to the archive

far2l/bootstrap/scripts/farlang.templ.m4, far2l/src/cfg/ConfigOpt.cpp, far2l/src/cfg/config.cpp, far2l/src/cfg/config.hpp, far2l/src/hist/history.cpp
Automatic assignment of single-button shortcuts to items of dynamically changing lists are quite misclick prone and in a case of commands history even could be dangerous. 
Not sure if it's useful for most users, but I'd like to have an option to disable. Here it is
=> Option to disable automatic highlights in history lists

.github/workflows/artifacts.yml, .github/workflows/build.yml
Workflow для проверки сборки far2l.
Особенности:
1. проверка на низкой и высокой версии компиляторов gcc/clang x64 , для возможности как гарантировать сборку на старых системах, так и быть готовым к новым. GCC - 9, 13.  Clang - 10, 15
2. проверка на Arm64 платформе macos 14 , Clang 15
3. полная сборка, со всеми плагинами. за исключением libunrar
4. параллельная сборка, для ускорения
5. вызывается на Pull Request и push в master.
6. можно запустить вручную, в том числе и на любом бранче. Что полезно при тестировании на fork репозиториях
7. не реагирует на изменение в master "не значимых файлов" (paths-ignore)
По хорошему надо удалить .github/workflows/artifacts.yml, т.к. он дублирует, проверяет не все конфигурации, срабатывает на любой push , зачем-то хранит артефакты сборки (в истории уже …
=> Check build with GitHub Action workflow

colorer/CMakeLists.txt, colorer/src/Colorer-library/src/CMakeLists.txt, colorer/src/Colorer-library/src/colorer/common/Features.h.in, colorer/src/Colorer-library/src/colorer/parsers/ParserFactoryImpl.cpp, colorer/src/Colorer-library/src/colorer/platform/filesystem.hpp, colorer/src/Colorer-library/src/colorer/strings/icu/UStr.cpp, colorer/src/Colorer-library/src/colorer/strings/icu/UStr.h, colorer/src/Colorer-library/src/colorer/strings/icu/common_icu.h, colorer/src/Colorer-library/src/colorer/strings/legacy/UStr.cpp, colorer/src/Colorer-library/src/colorer/strings/legacy/UStr.h, colorer/src/Colorer-library/src/colorer/utils/Environment.cpp, colorer/src/Colorer-library/src/colorer/utils/Environment.h, colorer/src/Colorer-library/src/colorer/xml/BaseEntityResolver.cpp, colorer/src/Colorer-library/src/colorer/xml/LocalFileXmlInputSource.cpp, colorer/src/Colorer-library/src/colorer/xml/XmlInputSource.cpp, colorer/src/Colorer-library/src/colorer/xml/XmlInputSource.h
To build, we use our 'own' std::filesystems implementation.
Building far2l is now possible again on gcc-7 (ubuntu 18.04)
=> Build Colorer without std::filesystem

far2l/src/dialog.cpp
Из-за забытой инверсии, в некоторых диалогах сразу несколько кнопок могли быть подсвечены, будто бы они в фокусе.
=> fix incorrect initial focus highlighting in dialogs

far2l/src/findfile.cpp
При сканировании файла, спроецированного в память, не учитывалась **точная** верхняя граница поиска, заданная переменной SearchInFirst. В итоге в результат поиска файлов попадали лишние файлы, содержащие искомый шаблон, но за пределами указанного пользователем ограничения (поиск вёлся во всём "последнем" окошке из проекции).
=> ScanFileByMapping fix: take into account the exact upper boundary

multiarc/configs/plug/custom.ini, multiarc/src/formats/7z/7z.cpp
The 7zz tool, often supplied in the 7zip package, offers a more recent port of 7zip for Linux compared to the p7zip package version.
=> Add support for 7zz tool (more recent 7zip port)

far2l/bootstrap/scripts/farlang.templ.m4, far2l/src/cfg/ConfigOpt.cpp, far2l/src/cfg/config.cpp, far2l/src/cfg/config.hpp, far2l/src/hist/history.cpp
Default behavior change to new "if Name and Extra equal"
Added toggle in System settings: "by Name and extra" and "by name"
Теперь вот так:
Настройка варианта удалению из истории "по имени и пути" давно напрашивалась, а то случайно не в том каталоге запустишь и потом ищи где оно было. Настройку "никогда" добавил до кучи, ибо она легко тут вписалась.
=> History - delete duplicates if Name and Extra equal

far2l/src/dirinfo.cpp
fix https://github.com/elfmz/far2l/issues/2207 : prevent PANIC-PANIC crash during Quick view (Ctrl+Q) or size calculating (F3) of a directory containing inaccessible folders
=> fix 2207: prevent crash on Quick View and when calculating folder size

far2l/src/setattr.cpp
=> Attributes dialog CtrlA: dynamically show marks (*) near changed fields + refactoring

far2l/src/hist/history.cpp
After #2241 history may have duplicate names, which should not influence on autocomplete
=> History - fix duplicates in autocomplete after #2241

far2l/bootstrap/scripts/farlang.templ.m4, far2l/src/cfg/ConfigOpt.cpp, far2l/src/cfg/config.hpp, far2l/src/findfile.cpp
Fix part of #2029
Данный PR вроде работает, но ощущение, что код "сырой" и возможно при вмерживании как-то подправить напильником, например там где забирается маска и преобразуется в нижний регистр.
Я, минимально меняя текущую логику, наложил костыль именно при нечувствительности принудительного сводя к нижнему регистру. Но может вообще не надо костылить через смену регистра на этом уровне?
Также расположение дополнительной галочки учёта регистра в масках спорно - оно оторвано от остальных галочек, но зато она рядом с самой маской и их недалеко вместе менять и не приходится мучится сокращать длину текста подписи галочки на некоторых размашистых языках.
=> Customize Case (in)sensitive option for file masks in Find file

far2l/bootstrap/scripts/farlang.templ.m4, far2l/src/filefilterparams.cpp, far2l/src/filemask/BaseFileMask.hpp, far2l/src/filemask/CFileMask.cpp, far2l/src/filemask/CFileMask.hpp, far2l/src/filemask/FileMasksProcessor.cpp, far2l/src/filemask/FileMasksProcessor.hpp, far2l/src/filemask/FileMasksWithExclude.cpp, far2l/src/filemask/FileMasksWithExclude.hpp, far2l/src/findfile.cpp, far2l/src/mix/processname.cpp, far2l/src/mix/processname.hpp, far2l/src/panels/filelist.cpp
По мотивам обсуждений в https://github.com/elfmz/far2l/issues/2029.
- Логика регистро(не)зависимого сличения с маской перенесена в `CmpName_Body()`, поиск файлов по Alt-F7 и пометка файлов на панели по Gray+ полагается теперь на это.
- Обновлены сигнатуры методов `Compare` у BaseFileMask, CFileMask, FileMasksProcessor, FileMasksWithExclude путём добавления нового параметра bool ignorecase с дефолтным значением true.
- Скорректированы вызовы методов `Compare`.
- Обновлён farlang.templ.m4: добавлено уточнение "(text)" для чекбокса учета регистра искомой подстроки в содержимом файлов.
<hr>
При просмотре оригинальной CmpName_Body() была обнаружена любопытная деталь.
Часть процессинга одной и той же маски она осуществляла регистро**независимо** (например, …
=> Case sensitive fix & improvements

NetRocks/src/PluginImpl.cpp
For site connections list don't use current far2l panel modes:
always only 1 column (name) without dependence on panel Align file extensions
New behaviour close to far3 NetBox
Before was annoying if panel mode has Align file extensions
Now: always all name together
=> NetRocks: for site connections list don't use current far2l panel modes

far2l/src/macro/macro.cpp
actual:
panelselectFunc, ReplaceStrings "\r\n" (CRLF) with ;
added:
panelselectFunc, ReplaceStrings "\r" (CR) with ;  
panelselectFunc, ReplaceStrings "\n" (LF) with ;  
This allow to select multiple files separated by CRLF but also separated by CR or LF from FarEncyclopedia.ru.chm::/html/macro/macrocmd/prop_func/panels.html
N=panel.select(panelType,Action[,Mode[,Items]])
Panel.Select(0,1,2,clip(0))
выделить элементы, имена которых содержатся в буфере обмена 
;;
Can be used in
.config\far2l\settings\key_macros.ini
[KeyMacros/Shell/CtrlS]
Description=Select from clipboard
DisableOutput=0x1
EmptyCommandLine=0x1
Sequence=Panel.Select(0,1,2,clip(0))
=> macro.cpp; panelselectFunc; allow to select multiple files

far2l/bootstrap/scripts/farlang.templ.m4, far2l/src/filefilter.cpp, far2l/src/filefilterparams.cpp, far2l/src/filefilterparams.hpp, far2l/src/hilight.cpp
Добавляет опцию учёта регистра в масках файлов в файловый фильтр (в диалогах по Gray+/поиска/копирования/etc,  а также в фильтрах раскраски файлов).
=> Add "Case sensitive" option to FileFilter

colorer/src/pcolorer2/pcolorer.cpp
init main variable on startup
ps. but I still don't understand why after unloading and loading the plugin the "old" memory was used
=> fix Plugin Colorer crashes #2277

colorer/src/pcolorer2/FarEditor.cpp, colorer/src/pcolorer2/FarEditor.h, far2l/far2sdk/farplug-wide.h, far2l/src/editor.cpp
При исправлении https://github.com/elfmz/far2l/commit/c2f9644c507ca9d70c02c8640c8ed4ee0b52ca80 для https://github.com/elfmz/far2l/issues/1941 было изменено API для задания цвета. Что стало приводить к проблемам с раскраской на некоторых типах файлов в Colorer. 
так же это Api не документиовано, и расходится с тем что есть в far3.
изначальаня поблема правится силами Colorer, по аналогии с far3.
так же тут поправлено заполнение части строки без текста, в случае использования truemod , подчеркивания текста
=> Artifacts in editor

far2l/bootstrap/wslgclip.sh
=> fix redundant newlines appearing at the end of clipboard content

far2l/src/dialog.cpp, far2l/src/edit.cpp, far2l/src/fileedit.cpp, far2l/src/fileview.cpp, far2l/src/mix/strmix.cpp, far2l/src/mix/strmix.hpp, far2l/src/panels/panel.cpp, far2l/src/plug/PluginA.cpp, far2l/src/plug/PluginW.cpp, far2l/src/plug/plugins.cpp, far2l/src/vmenu.cpp
* More accurate check index from plugin's dialog (from far2m)
from https://github.com/shmuz/far2m/commit/a1011fffe7690ac9c200ce7d4fc7a78840f695eb
* Fix CmdLine.CurPos (from far2m)
from https://github.com/shmuz/far2m/commit/f87f896d268e8f879d7fcbafedccc14e29e1c2bb
* Fix ShiftF2 & ShiftF3 operation when multiple plugins-archivers are present (from far2m)
from https://github.com/shmuz/far2m/commit/8373f33d9d61fb0f30d873b2f2f3514b0d3958e6 & https://github.com/shmuz/far2m/commit/afed4357a5686dbe27b8ab0a7750f5ed4eae2037
* Fix a crash bug in VMenu (from far2m)
from https://github.com/shmuz/far2m/commit/f569ac5aaaddadda32480bbd9d3bdda49cf1e823
* Free memory after canceling F6 in the Viewer (Mantis 2605) (from far2m)
from https://github.com/shmuz/far2m/commit/d0469e3de45611040479881f0cf55e3c0c2e8f4 …
=> Miscellaneous fixes from far2m

far2l/bootstrap/wslgclip.sh
fixes weird issue in WSL clipboard processing. found in chat:
https://t.me/far2l_ru/26099
```
CONTENT="$(cat)"
```
When we use this construct, the shell executes the `cat` command, reads its output, and assigns it to the `CONTENT` variable. However, the shell removes trailing newlines. This is the default behavior for variable assignments in the shell.
So we need to take care of it:
```
CONTENT=$(cat; echo -n .)
CONTENT=${CONTENT%.}
```
=> fix newlines in wsl clipboard processing

WinPort/src/Backend/TTY/TTYInput.cpp, WinPort/src/Backend/TTY/TTYInputSequenceParser.cpp, WinPort/src/Backend/TTY/TTYInputSequenceParser.h, WinPort/src/Backend/TTY/TTYInputSequenceParserExts.cpp
Fix for a https://github.com/elfmz/far2l/pull/2085 fix, which fixes #2072. Also fixes #2329.
Actually, #2329 was `ESC [200~` and `ESC [201~` (bracketed paste mode) double encoding problem. I made universal double encoding handling, not mouse only.
=> win32-input-mode double encoding fix

far2l/src/vt/vtshell_translation.cpp
Bring escape sequences generated in VT on [Alt|Ctrl|Shift]+F1..F4 key presses closer to generated by GNOME terminal. Fixes #2330
=> More compatible esc sequences on [Alt|Ctrl|Shift]+F1..F4 keypresses

multiarc/src/formats/ha/ha/machine.c, multiarc/src/formats/ha/ha/machine.h, multiarc/src/formats/ha/ha/md_funcs.txt
In Debian and Ubuntu, `time_t` is now 64 bit (`long long`) on 32-bit architectures (except for deprecated i386 architecture).
So trying to pass `long *` to localtime(3) which accepts `time_t *` causes a compiler error, because trying to use such a pointer would cause out of bounds read:
https://buildd.debian.org/status/fetch.php?pkg=far2l&arch=armhf&ver=2.6.3%7Ebeta%2Bds-1&stamp=1723367125&raw=0
To fix this, change the signature of `md_timestring` and get rid of the pointer cast.
=> Make md_timestring accept time_t

far2l/src/macro/macro.cpp, far2l/src/plug/plugins.cpp, incsrch/REG/^#enter.reg, incsrch/REG/^enter.reg, incsrch/key_macros.ini
We are checking if we are inside a plugin by testing CurPluginItem. This does not have a value until OpenPlugin returns a handle. It is a common practice to perform all work inside a non-panel, non-persistent plugin within its OpenPlugin call and return INVALID_HANDLE_VALUE.
There is PSIF_ENTERTOOPENPLUGIN flag, but we do not set it. The fix is to set it and check it.
Fixes https://github.com/elfmz/far2l/issues/2325, but it also needs a change in the ~/.config/far2l/settings/key_macros.ini to include NoSendKeysToPlugins=0x1 which has replaced NoInsidePlugin back in
2003. Added incsrch/key_macros.ini for convenience to add to the key_macros.ini. Please refer to bug #2325 for in deep details.
=> Fix CheckInsidePlugin for non-panel plugins

utils/include/Escaping.h
fix #2344 (Incorrect work with folder named with `)  :  escape backticks too
=> fix #2344: escape backtick character

far2l/src/vt/IVTShell.h, far2l/src/vt/vtansi.cpp, far2l/src/vt/vtshell.cpp
Enough to use far2l comfortably though.
Test with
```
far2l --tty --nodetect
```
under far2l with this improvement applied.
Tested with [FreeVision kitty protocol implementation](https://gitlab.com/freepascal.org/fpc/source/-/issues/40673) and [turbo](https://github.com/magiblot/turbo) also.
Fixes #2035.
=> (basic) support of kitty keyboard protocol in VT

cmake/modules/Findfmt.cmake
After upgrading from fmt 10.x.x to 11.x.x in openSUSE, compilation of the colorer plugin caused cmake errors.   fmt 11.x.x stores version in new file fmt/base.h.
Update Findfmt.cmake to be compatible with fmt 11.x.x
=> Update Findfmt.cmake for compatibility with fmt 11.x.x

WinPort/src/Backend/TTY/TTYBackend.cpp, WinPort/src/Backend/TTY/TTYBackend.h, WinPort/src/Backend/WinPortMain.cpp
As number of users who prefer not to press ESC twice is probably much greater than number of users who want to send custom escape sequences to far2l (can't even imagine a use case for that), let's enable --ee=100 by default, allowing user to disable this feature if needed for some reason
=> esc expiration on by default, officially

far2l/src/vt/VTFar2lExtensios.cpp, far2l/src/vt/vtshell.cpp
After 1st default button only for stub thoughtless action:
=> Prevent quick thoughtless tap Enter or Space or Esc in dialog

CMakeLists.txt, README.md, bash-completion/CMakeLists.txt, bash-completion/far2l
Не уверен, что такое безусловное включение bash-completion в CMakeLists.txt будет корректно во всех системах.
Может надо какие-то доп.проверки на `CMAKE_XDGDATA_DIR`?
У меня закидывание файла bash-completion/far2l в `/usr/share/bash-completion/completions/` даёт вроде адекватное автодополнение для far2l в bash.
=> Add bash-completion & minor readme

.github/workflows/build.yml, .travis.yml, README.md, packaging/CMakeLists.txt
#2052
В дистрибутивах возвращаются к истокам и отказываются от ложного переименования пакетов.
=> Issue #2052: migrate dependencies from pcre3 back to pcre2 library

far2l/src/panels/filelist.cpp
fix #2405
from: https://github.com/shmuz/far2m/commit/d041d0e2a7198eb874c08ce6025f8d737b33826c
=> fix #2405: fix panel sorting bug

far2l/src/fnparce.cpp
from: https://github.com/shmuz/far2m/commit/5505cd64b07adb89a1cca58cb1b92a1690dbd4b9
revert https://github.com/elfmz/far2l/commit/31ba3e9160ab63aba51d716fcc322dff38b6d230 as it breaks special symbols from user input dialog
=> Revert commit (from far2m / Mantis 0002845)

far2l/src/vt/vtcompletor.cpp
fix #2394
**TL;DR**
[Очистка](https://github.com/elfmz/far2l/blob/adca1222934b1615ccde37cf41a9fa2c3a8022b0/far2l/src/vt/vtcompletor.cpp#L243-L245) переменной reply в VTCompletor::TalkWithShell() не срабатывает из-за '\n',  [добавленного](https://github.com/elfmz/far2l/blob/adca1222934b1615ccde37cf41a9fa2c3a8022b0/far2l/src/vt/vtcompletor.cpp#L172) к магическому маркеру begin, так как в содержимом reply — "\r\n".
<details>
<summary> <b>Подробнее ...</b> </summary>
Проблема возникает в функции [VTCompletor::TalkWithShell()](https://github.com/elfmz/far2l/blob/adca1222934b1615ccde37cf41a9fa2c3a8022b0/far2l/src/vt/vtcompletor.cpp#L163-L258), используемой двумя другими, ExpandCommand() и GetPossibilities().
В первом случае из [issue #2394](https://github.com/elfmz/far2l/issues/2394) _(с …
=> fix #2394: autocompletion fix

far2l/src/vt/vtcompletor.cpp
fix #2425
Согласно [readline(3)](https://www.man7.org/linux/man-pages/man3/readline.3.html):
>  show-all-if-ambiguous (Off)
> 
> This alters the default behavior of the completion functions. If set to On, words which have more than one possible completion cause the matches to be listed immediately instead of ringing the bell. 
>  
>  show-all-if-unmodified (Off)
> 
> This alters the default behavior of the completion functions in a fashion similar to show-all-if-ambiguous. If set to On, words which have more than one possible completion without any possible partial completion (the possible completions don't share a common prefix) cause the matches to be listed immediately instead of ringing the bell.
Код far2l не рассчитан на работу с такими настройками. Метод VTCompletor::ExpandCommand() …
=> fix #2425: autocomplete garbage if show-all-if-ambiguous is On

far2l/src/console/scrbuf.hpp, far2l/src/execute.cpp
fix #2410
Решение позаимствовано у https://github.com/shmuz/far2m/commit/1a24cc0f5dca06ae40a3398c14c2a90879bed9f1, за исключением макроса [SCOPED_ACTION](https://github.com/shmuz/far2m/blob/5d26f64bd8f05ea284e5195d27aeeb4216635fc6/far/src/headers.hpp#L179-L187), его пока перетягивать не стал, хотя можно и подумать. Макрос, в свою очередь, пришел из FAR3.
=> fix #2410, Strange behavior for NumEnter (screen redraw issue)

far2l/src/main.cpp
fix #2430
Решение позаимствовано из far2m: [1](https://github.com/shmuz/far2m/blob/5d26f64bd8f05ea284e5195d27aeeb4216635fc6/far/src/main.cpp#L137-L169) [2](https://github.com/shmuz/far2m/blob/5d26f64bd8f05ea284e5195d27aeeb4216635fc6/far/src/main.cpp#L246-L252)
Поскольку текущий файл на панели теперь устанавливается в функции `UpdatePathOptions()` через `Opt.strLeftCurFile`/`Opt.strRightCurFile`, ветки с вызовом `GoToFile()` стали неактуальными и (возможно временно) закомментированы. 
Также под раздачу попал вызов `ProcessKey(KEY_CTRLPGDN)` в этих же ветках. 
Не уверен, стоит ли его оставлять. Inside по `Ctrl+PgDn` будет пытаться также зайти, например, в elf-ы вместо простого позиционирования на выполняемом файле. Не уверен, что это то, что нужно.
=> fix #2430: Incorrect files processing in far2l command line

WinPort/src/Backend/WX/wxMain.cpp
At least in Cinnamon and KDE.
Btw, [according to docs](https://docs.wxwidgets.org/3.2/group__group__funcmacro__misc.html#ga82a18ac43492bfb375604c41b71ce84f), it should not work under X11 at all. See #2294 for details.
Fixes #2294.
=> wxGetKeyState() fails to return correct Alt state under X11 in some cases

python/configs/plug/plugins/yfar.py, python/configs/plug/plugins/yjumpword.py
yfar python library extended with editor support
yjumpword python plugin added as an example editor plugin for yfar
This plugins allows to quickly jump back and forth between alpha-numeric words (identifiers). Useful when bound to hotkeys like Ctrl+Alt+Up / Ctrl+Alt+Down.
Also allows to show all lines with word under cursor.
=> yjumpword python plugin added, yfar library updated

WinPort/src/Backend/WX/wxMain.cpp
As it is reported in #2124, wxWidgets/wxWidgets#23421 is not reproduced under Wayland. So let us do not apply workaround on Wayland systems to minimize risk of possible misbehavior.
=> Do not apply Alt+letter workaround under Wayland

WinPort/src/Backend/TTY/TTYInputSequenceParser.cpp, WinPort/src/Backend/TTY/TTYInputSequenceParserExts.cpp, WinPort/src/Backend/WX/wxMain.cpp, WinPort/src/Backend/WX/wxMain.h
Фикс для ввода кода символа через Alt+цифры теперь применяется только к цифрам NumPad'а — должно убрать риск глюков в других местах.
А обход неправильной раскладки клавиатуры для Alt+букв — только для клавиш, которые вводят буквы, и только на версиях wx, где оно надо. А ещё этот баг проявляется и на Wayland тоже, так что убрал лишнее условие про него.
И заодно поправил 5 на NumPad'е в kitty — без NumLock эта кнопка не работала на ввод кода символа.
=> Localize usage of recent workarounds

far2l/bootstrap/ps.sh
`read -n` is not supported in dash (Ubuntu's default) and is undefined in posix sh.
Another option was to change the shebang to bash (and leave the ability to interrupt the pause by pressing any key, not just `<Enter>`). But I think a more universal solution would be preferable.
=> ps.sh: improve posix sh compatibility

far2l/src/vmenu.cpp
Fix redraw in filtered menu (see Mantis [#0001794](https://bugs.farmanager.com/view.php?id=0001794))
from https://github.com/shmuz/far2m/commit/c0778ae8a9952677e5c0cca548a6a54520803f8f
=> Fix redraw in filtered menu (see Mantis 0001794)

CMakeLists.txt
C/CXX flags get passed twice to the compiler in Release build.
=> cmake: fix doubled flags

far2l/src/editor.cpp
around line number 21475226 which gives integer overflow when multiplied by 100
```
Process 23391 stopped
* thread #8, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
frame #0: 0x000000010031a21c far2l`FARString::Content::Create(nCapacity=184467440737095499) at FARString.cpp:125:19
122 		Content *out = (Content *)malloc(sizeof(Content) + sizeof(wchar_t) * nCapacity);
123 		//Так как ни где выше в коде мы не готовы на случай что памяти не хватит
124 		//то уж лучше и здесь не проверять, а сразу падать
-> 125 		out->m_nRefCount = 1;
126 		out->m_nCapacity = (unsigned int)std::min(nCapacity, (size_t)std::numeric_limits<unsigned int>::max());
127 		out->m_nLength = 0;
128 		out->m_Data[0] = 0;
Target 0: (far2l) stopped.
(lldb) bt
* thread #8, stop reason = EXC_BAD_ACCESS (code=1, …
```
=> Crash on overflow when searching in a large file

inside/configs/plug/config.ini, inside/src/inside.cpp
It would be useful to support reading PE format. [readpe](https://repology.org/project/readpe/versions) is available in debian/ubuntu.
Also added for png, ogg, m4a.
=> inside: add PE format

tmppanel/src/TmpPanel.cpp
Фикс функционала "Меню из файла-списка".
<details>
<summary>Из справки.</summary>
<hr>
<p>При открытии файла списка его содержимое будет помещаться не в панель, а в меню. Нажатие Enter на каком-либо пункте меню либо переходит в соответствующий каталог (если он существует), либо копирует текст пункта в командную строку FAR. Заголовок меню равен имени файла-списка без расширения.</p>
<p>Каждая строка в файле-списке может начинаться на |&lt;string&gt;|. В таком случае отображаться в меню будет часть строки с первого до второго разделительного символа, а выполняться при выборе пункта - часть строки после второго разделительного символа.</p>
<p>|-| служит разделителем и будет отображаться в меню как горизонтальная линия.</p>
<hr>
</details>
1. В lstrcmp первым аргументом передавался param со …
=> tmppanel: fix PANIC-PANIC crash in menu from file list

colorer/src/Colorer-library/src/CMakeLists.txt, colorer/src/Colorer-library/src/colorer/base/BaseNames.h, colorer/src/Colorer-library/src/colorer/common/Logger.h, colorer/src/Colorer-library/src/colorer/utils/Environment.h, colorer/src/Colorer-library/src/colorer/utils/FileSystems.h, colorer/src/Colorer-library/src/colorer/xml/libxml2/LibXmlReader.cpp
Портировал к upstream Colorer-library себе изменения из 4369fb07405b2e81e0a4d92e6dcf1f44aea86bd1 , после чего проверил на разных платформах. Теперь автоматически проверяется на gcc7/clang7 , на которых ранее не собиралось.
рекоендуется применить после https://github.com/elfmz/far2l/pull/2515
=> sync colorer with upstream

tmppanel/src/TmpClass.cpp, tmppanel/src/TmpClass.hpp, tmppanel/src/TmpMix.cpp, tmppanel/src/TmpPanel.cpp
**1.  Багфикс парсинга параметров командной строки**: fix #2518
Источником проблемы является фрагмент:
https://github.com/elfmz/far2l/blob/63ae9f69971be435945edf244cc124225057b8db/tmppanel/src/TmpPanel.cpp#L96-L102
В `tmpTMP` копируется подстрока из `argv`, не содержащая завершающий `'\0'` (на его месте — пробел). Это приводит к некорректному сравнению функцией `lstrcmpi` из-за выхода за пределы буфера.
**2. Реализован функционал OpenPanelFromOutput().**
Загрузка результатов выполнения команды во временную панель или меню, например:
`tmp:<ls -1a`
Из оригинальных фич плагина пока не реализовано произвольное задание рабочего каталога, т.е. такая команда не сработает:
`tmp:<|/bin|ls -1a`
(впрочем, описание такого синтаксиса в хелпе отсутствует).
Сделано по аналогии с …
=> tmppanel: fixes, improvements, refactoring

WinPort/src/Backend/TTY/TTYBackend.cpp
planned to also add ESC sequences for kitty and iTerm2, but do not understand how to send them from here
see #1101
=> basic system tray notifications support in plain TTY mode

far2l/src/findfile.cpp
Fix #2526
Crash report on Mac shows the following callstaks
```
Thread 4 Crashed:
0   libsystem_kernel.dylib        	       0x1842ce600 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x184306f70 pthread_kill + 288
2   libsystem_c.dylib             	       0x184213908 abort + 128
3   libsystem_malloc.dylib        	       0x18411d524 malloc_vreport + 896
4   libsystem_malloc.dylib        	       0x1841454a8 malloc_zone_error + 100
5   libsystem_malloc.dylib        	       0x18414433c free_tiny_botch + 40
6   far2l                         	       0x100dfe060 PluginA::FreeOpenPluginInfo() + 56 (PluginA.cpp:998)
7   far2l                         	       0x100e02128 PluginA::ConvertOpenPluginInfo(oldfar::OpenPluginInfo&, OpenPluginInfo*) + 36 (PluginA.cpp:1034)
8   far2l …
```
=> Crash on concurrent access to temp directory

WinPort/src/ConsoleInput.cpp
How to Reproduce:
FreeBSD 14.1-RELEASE-p6 amd64
Open any file in the internal editor, switch the layout to any cyrillic, type "." (the [?/] key in the latin layout), and get the application crash. The fix is quite obvious - always check array ranges before accessing an item. The patch may not be perfect (because "." is not working in cyrillic layout), but at least it prevents crashing.
=> ConsoleInput: fix crash when dot is pressed in cyrillic layout

far2l/far2sdk/farplug-mb.h, far2l/far2sdk/farplug-wide.h, far2l/src/execute.cpp, tmppanel/src/TmpPanel.cpp
tmppanel:
1. tweak open/execute logic in ShowMenuFromList()
2. added keyboard shortcut help in ShowMenuFromList() 
3. Add a new flag `EF_EXTERNALTERM` to the [EXECUTEFLAGS](https://github.com/elfmz/far2l/blob/2c03f3a1d547c1c771f1880134da6ce64630f967/far2l/far2sdk/farplug-wide.h#L1979-L1988) enum to make possible  running commands in an external terminal by invoking `open.sh` with `exec` param  within  [farExecuteASynched()](https://github.com/elfmz/far2l/blob/2c03f3a1d547c1c771f1880134da6ce64630f967/far2l/src/execute.cpp#L290-L319)
=> tmppanel: tweak open/execute logic in ShowMenuFromList()

NetRocks/src/Protocol/SplitLocationSpecification.cpp
В коде разбора URL
https://github.com/elfmz/far2l/blob/1cf67b92894cae5176e8d45c60f0bcb401d037df/NetRocks/src/Protocol/SplitLocationSpecification.cpp#L43-L50
к паролю в начале цепляется лишний символ двоеточия, из-за чего набранные в командной строке адреса вида
`ftp://johndoe:123456@192.168.1.2:12345`
вызывают показ окна авторизации с просьбой ввести логин с паролем заново.
Фикс простой, но не уверен, что какой-то другой код не полагается на такой (неправильный) парсинг.
=> NetRocks: fix incorrect password parsing in SplitLocationSpecification()

utils/CMakeLists.txt
1. The `add_custom_target` command was replaced with `add_custom_command`.
2. ICU package is now found using `find_package(ICU COMPONENTS uc REQUIRED)`.
4. The command to generate character classes now uses ICU library (`${ICU_LIBRARY}`).
The custom target now depends on the generated character classes file, ensuring proper rebuilds when necessary.
=> improvement: optional ability to use icu available on build system

WinPort/src/Backend/TTY/TTYInputSequenceParser.cpp
Konsole 24.12 / KDE Plasma 6.2.4 / X11 generates `\x1b[[E` on F5
Also does Linux kernel console.
=> F5 is broken in Linux kernel console and recent KDE Konsole. This PR fixes that

WinPort/src/Backend/TTY/TTYBackend.cpp, WinPort/src/Backend/TTY/TTYBackend.h, WinPort/src/Backend/TTY/TTYInputSequenceParser.cpp, WinPort/src/Backend/TTY/TTYInputSequenceParser.h, WinPort/src/Backend/TTY/TTYOutput.cpp, WinPort/src/Backend/WX/wxMain.cpp, far2l/src/vt/IVTShell.h, far2l/src/vt/vtansi.cpp, far2l/src/vt/vtshell.cpp, far2l/src/vt/vtshell_ioreaders.cpp, far2l/src/vt/vtshell_ioreaders.h
WinPort: Implement FOCUS_EVENT  delivering on focus state changes, TTY backend uses [?1004h mode for this
VT: propogate FOCUS_EVENT to application if it requested focus events by [?1004h
! This change caused KEY_GOTFOCUS/KEY_KILLFOCUS to be delivered to all dialogs again, be aware as this events wasnt functional since porting moment
=> TTY/VT: focus change notifications  (touch #2563)

far2l/bootstrap/scripts/far2l_m4.pl, far2l/bootstrap/scripts/farver.pl
This fixes failure to build reproducibly, which can be seen in Debian: https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/far2l.html
See https://reproducible-builds.org/ for details.
Cc @alexmyczko
=> Add support for SOURCE_DATE_EPOCH environment variable

WinPort/src/Backend/TTY/TTYOutput.cpp
fixes shaping in Linux kernel console (and probably iTerm2)
=> fix cursor shaping in Linux kernel console (and probably iTerm2)

far2l/CMakeLists.txt, far2l/DE/far2l-wx.desktop, far2l/DE/far2l.desktop, far2l/DE/far2ledit-wx.desktop
Terminal versions need `Terminal=true`, GUI versions need `Terminal=false`.
The old `far2l.desktop` had `Terminal=false`, which means that if WX interface is not available, far2l would start in background without any window.
The old `far2ledit.desktop` had `Terminal=true`, which means that if WX interface is available, far2l would open both terminal and its own window.
To fix these problems, create separate desktop files and pass `--tty` and `--notty` explicitly.
In the menu, there will be 4 items, like on this screenshot:
As requested by @akruphi, also added `System` and `FileTools` categories to far2l desktop files, per analogy with `mc.desktop` which has them.
=> Use separate desktop files for TTY and GUI versions

far2l/src/panels/qview.cpp
fix #2581
Пока быстрофикс. Но можно и заморочиться, сделать вывод инфы с именем ссылки и тем, что она битая.
И то же самое для сокетов, каналов, символьных и блочных устройств.
Как сейчас сделано — оно не очень красиво выходит: когда со включённым Quick View листаешь файлы и натыкаешься на эти исключения, то инфа не обновляется, остаётся для предыдущего файла/директории.
=> fix #2581: Far2l crash in Quick view when try show broken symlink

far2l/src/main.cpp
Поднял проверку локализации выше по коду, чтобы она встала перед `CtrlObj.Init();` в 254 строке. 
Нам нужно, чтобы опция локализации была правильно установлена до начала отрисовки интерфейса, инче панели нарисуются согласно дефолтными параметрам на английском.
I raised the localization check higher in the code so that it comes before `CtrlObj.Init();` in line 254. We need the localization option to be set correctly before the interface begins to be drawn, otherwise the panels will be drawn according to the default parameters in English.
=> fix incorrect interface locale on first render

WinPort/src/Backend/TTY/TTYOutput.cpp
- removed irrelevant comment (it was screen tool related, not FreeBSD kernel console related)
- added relevant comment (links to resources related to cursor shape modification escape sequences)
fixes #2571
=> - remove irrelevant comment

python/configs/plug/plugins/tool-show-clipboard.py, python/configs/plug/plugins/ucharmap.py, python/configs/plug/plugins/uclipget.py, python/configs/plug/plugins/uclipset.py
copy/paste files via clipboard - wx ONLY version - with support for gnome clipboard types, works with gnome files/nautilus
Marked files (Ins) in active panel are copied to clipboard after running "Python clip SET" plugin (py:load uclipset)
After running "Python clip GET" plugin (py:load uclipget) files are copied from clipboard to current filespanel
tool-show-clipboard.py allows you to see what's in the clipboard
ucharmap.py - shows then whole unicode characterset
=> python clipboard - wx winport version

far2l/src/clipboard.cpp
The return value of malloc() is often checked for NULL in far2l code.
The value ```CharsCount``` in Clipboard::Paste() could be large, causing malloc() to return NULL.
There is a check ```if (ClipText) {``` on line 229.
Therefore, I added an additional check.
=> Fix potential NULL dereference in clipboard.cpp

NetRocks/CMakeLists.txt
Updating libnfs from version 5.x.x to 6.0.x in Arch Linux leads to errors when building the application.
New libnfs 6.0.x requires gnutls library.
Update NetRocks' CMakeLists.txt file to ensure compatibility with libnfs version 6.0.x and above by adding the libgnutls library to the list of linked libraries.
=> Update NetRocks libnfs 6.0.x compatibility

python/configs/plug/far2l/fardialogbuilder.py, python/configs/plug/plugins/read-en.txt, python/configs/plug/plugins/read-pl.txt, python/configs/plug/plugins/ucharmap.py, python/configs/plug/plugins/ucharmapold.py, python/configs/plug/plugins/uedindent.py, python/configs/plug/plugins/uedsort.py, python/configs/plug/plugins/ueduniq.py, python/configs/plug/plugins/uhexedit.py, python/configs/plug/plugins/usizer.py, python/configs/plug/plugins/usizerflow.py, python/configs/plug/plugins/uvtlog.py, python/configs/plug/plugins/yfar.py
- removed references to debugpy
- dialog can be created without borders
- proper numbering of dialog elements
- new plugin (WIP) hex editor
- other small fixes
=> python fixes and new plugin

far2l/CMakeLists.txt, far2l/bootstrap/scripts/farlang.templ.m4, far2l/src/about.cpp, far2l/src/chattr.cpp, far2l/src/chattr.hpp, far2l/src/main.cpp, far2l/src/message.cpp, far2l/src/message.hpp, far2l/src/mix/FSFileFlags.cpp, far2l/src/mix/FSFileFlags.h, far2l/src/options.cpp, far2l/src/panels/filelist.cpp, far2l/src/setattr.cpp
* new function `ExMessager::AddMultiline()` & tuning after #2576
* save errno after flags operations
* setattr (Ctrl-A) count devices + disable attributes/flags if was error
Возможно странно ловятся ошибки работы с атрибутами: для устройств или любых файлах на разделах, не поддерживающих атрибуты, - ловятся, а для симлинков на обычных разделах нет ошибки, хотя и **lsattr** и **mc->File->chattr** на них также ругаются кодом 95 "Operation not supported". ~Но по всей навороченной касакдности вызовов внутри far2l (`sdc_fs_flags_get` обернутое вокруг `bugaware_ioctl_pint`) я запутался теряются ли там errno или просто lsattr не умеет, то что умеет ext4.~
_Разобрался_ - см. ниже **UPD3**.
* **UPD:** Новый диалог для выставления известных мне из `<linux/fs.h>` и `<sys/stat.h>` атрибутов/флагов. …
=> Chattr / chflags dialog + misc

far2l/bootstrap/scripts/farlang.templ.m4, far2l/src/cfg/ConfigOpt.cpp, far2l/src/cfg/config.cpp, far2l/src/cfg/config.hpp, far2l/src/editor.cpp, far2l/src/mix/panelmix.cpp, far2l/src/panels/filelist.cpp, far2l/src/panels/filelist.hpp
Вместе с унаследованным UNC-кодом из far2l был также удалён функционал разрешения символических ссылок и получения реальных путей при процессинге хоткеев в панелях:
```
Вставить сетевое (UNC) имя файла из активной панели     Ctrl-Alt-F
Вставить сетевое (UNC) имя файла из пассивной панели    Ctrl-Alt-;
Вставить сетевой (UNC) путь из левой панели             Ctrl-Alt-[
Вставить сетевой (UNC) путь из правой панели            Ctrl-Alt-]
Вставить сетевой (UNC) путь из активной панели         Alt-Shift-[
Вставить сетевой (UNC) путь из пассивной панели        Alt-Shift-]
Поместить сетевые (UNC) имена помеченных файлов       Ctrl-Alt-Ins
в Буфер Обмена (без учёта состояния командной
строки)
5. Комбинации клавиш, позволяющие получить сетевое (UNC) имя файлового
объекта, работают по следующим …
```
=> Bring back symlink resolving via hotkeys, as in FAR2/3

far2l/src/vmenu.cpp
from: https://github.com/shmuz/far2m/commit/64454de160eb4fab17bdc2aa7b6558f0eebf81ce
fix #2082
=> Fix #2082 A fix for overlapping menus with panels (from far2m)

far2l/src/setattr.cpp
Диалог Ctrl-A:
1. Неправильно устанавливался владелец при рекурсивной обработке вложенных папок  (вместо имени владельца использовалось имя группы).
2. Некорректная индикация звёздочкой при изменении группы (вместо сравнения с именем исходной группы происходило сравнение с именем исходного владельца).
3. Рекурсивное выставление атрибутов _(Immutable / Append / Hidden)_ для вложенных папок должно было происходить, но не отрабатывало потому, что было размещено не под той веткой if, и выполнялось только в том случае, если одновременно менялись права доступа.
=> SetAttr: fix recursive file owner changing + wrong group mark indicating + recursive file attributes/flags changing

multiarc/src/arcread.cpp
Fix issue #2668:  Multiarc ignores archives if the archive file name does not have an extension - update arcread.cpp
Remove appending dot to archive filename
=> Fix issue #2668: Multiarc ignores some archives 

changelog.md
Надеюсь ничего существенного не пропустил.
~Позволил себе описать тут ещё не принятые PR - строки помечены _[if ... will be accepted]_, которые при слияния надо будет удалить~ - UPD: все приняты и тут также учел.
Ну и предлагаю всем делающим PR с новыми фичами / значительными улучшениями сразу внутри PR вносить описания и в changelog.md
=> Add changelog only with significant changes as user-readable text

.github/workflows/build.yml, _ci/Dockerfile.clang7, _ci/Dockerfile.gcc7
The Ubuntu 20.04 Actions runner image will begin deprecation on 2025-02-01 and will be fully unsupported by 2025-04-01  https://github.com/actions/runner-images/issues/11101
переделал сборку на использование doсker образа с нужными компиляторами.
как можно развить эту тему
- отказаться от сборки на старых версиях компиляторов, этот PR не нужен
- не зависить от базового образа в репе colorer (но я сам использую его), расширить образ включив туда нужные зависимости для far2l. Но это потребует больших настроек в текущем проекте - включить packages, настроить секреты, настроить сборку образа
=> ci: change gcc7 build test

changelog.md, far2l/bootstrap/scripts/farlang.templ.m4, far2l/src/cfg/ConfigOpt.cpp, far2l/src/cfg/config.hpp, far2l/src/fileowner.cpp, far2l/src/fileowner.hpp, far2l/src/setattr.cpp
Now any changing also reset owners/groups to original and not fully compatible with changing due to Process subfolders.
Also prohibition processing info and ownership for objects inside plugins which not in real local file system.
---
Повторяю просьбу по возможности выпустить релиз - вроде уже совсем край ещё протащить в Ubuntu 25.04 (подробности см. в https://github.com/elfmz/far2l/issues/2646 ).
Ну и в любом случае лучше заранее на большем числе архитектур и пользователей обкатать все нововедения пока в апреле не настанет заморозка Debian 13.
=> Setattr: ability to show "uname"/"gname" or "uid: uname"/"gid: gname"

changelog.md
Next time, please do it before the release. This way the generated `.metainfo` file in the release tarball will have an entry for the release.
=> changelog.md: Set release date for v2.6.5

CMakeLists.txt, far2l/bootstrap/CMakeLists.txt, packaging/debian/CMakeLists.txt
This fixes build with CMake 4.0.
See:
- https://cmake.org/cmake/help/latest/release/4.0.html#deprecated-and-removed-features
- https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#policy-version
=> Bump required CMake version to 3.5

packaging/version_bump_patch.sh
For the release commit/tag, `Master (current development)` is replaced with the new version number in the changelog.
After the tag, a separate commit is created to start a new changelog entry, so other developers can add their rows to it.
Proper formatting of changelog file is important because we generate a `metainfo` file from it, and `metainfo` file is used by software center applications and other services like Flathub.
=> version_bump_patch.sh: Also update changelog

WinPort/src/Backend/WX/wxClipboardBackend.cpp, python/configs/plug/plugins/uclipget.py
ClipboardAllocate should allocate as many bytes as the clipboard size, not one byte more.
Then ClipboardSize used to allocate the destination buffer adds one byte to the buffer size.
python plugins uclipget.py and uclipset.py also work in --tty session
=> FIX: ClipboardAllocate for non (unicode)text elements

WinPort/src/Backend/WinPortMain.cpp
When running in GNU Screen, enable "--norgb" switch by default to avoid unusable colours.
=> Bug fix:  When running in GNU Screen, enable "--norgb" switch by default to avoid unusable colours.

WinPort/src/Backend/WX/wxMain.cpp, far2l/src/vt/vtshell_translation_kitty.cpp
Our implementation of the Kitty protocol is still not fully compliant with the specification. One of the discrepancies was that when the Shift key was pressed, the `unicode-key-code` field contained values that didn't conform to the spec for all keys except alphabetic ones. After this commit, that field will contain 0 in such cases — which is not ideal, but still better than providing incorrect values. In any case, for character codes, applications should rely on the `shifted key` or `text-as-codepoints` fields that provide chars taking in mind Shift state, so this change should not affect real-world application behavior (tested it in the kitty mode of far2l and also in turbo).
=> Improvements of kitty protocol implementation

far2l/src/dialog.cpp, far2l/src/plug/plugapi.cpp
FAR API: fix crashing on invalid dialog coordinates (from far2m & Far3)
from: https://github.com/shmuz/far2m/commit/9868000e6a96ddee05fa0623240484865369ae76
& https://github.com/FarGroup/FarManager/blob/5f71f81412163821955049811aba544be5cbdcae/far/plugapi.cpp#L947-L951
=> From far2m

far2l/src/vt/vtshell_translation_kitty.cpp
Switched back to using shifted key value if unshifted is undetectable, as recommented by spec author in
https://github.com/kovidgoyal/kitty/issues/8620#issuecomment-2878530117
=> Align implementation to recent spec author recomendations

CMakeLists.txt, NetRocks/CMakeLists.txt, align/CMakeLists.txt, autowrap/CMakeLists.txt, calc/CMakeLists.txt, cmake/FuncCopyResources.cmake, colorer/CMakeLists.txt, compare/CMakeLists.txt, drawline/CMakeLists.txt, editcase/CMakeLists.txt, editorcomp/CMakeLists.txt, far2l/CMakeLists.txt, far2l/bootstrap/CMakeLists.txt, filecase/CMakeLists.txt, inside/CMakeLists.txt, multiarc/CMakeLists.txt, packaging/debian/CMakeLists.txt, tmppanel/CMakeLists.txt
errors appear on the latest version of cmake, such as:
```
CMake Warning (dev) at far2l/bootstrap/CMakeLists.txt:35 (add_custom_command):
COMMENT requires exactly one argument, but multiple values or COMMENT
keywords have been given.
Policy CMP0175 is not set: add_custom_command() rejects invalid arguments.
Run "cmake --help-policy CMP0175" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
```
```
CMake Warning (dev) at far2l/bootstrap/CMakeLists.txt:55 (add_custom_command):
The following keywords are not supported when using
add_custom_command(TARGET): DEPENDS.
Policy CMP0175 is not set: add_custom_command() rejects invalid arguments.
Run "cmake --help-policy CMP0175" for policy details.  Use the cmake_policy
command to set the policy and …
```
=> Fix cmake warnings

far2l/src/vt/vtshell.cpp
Output messages to the log not only when generating kitty sequences, but also win32-input-mode ones. Now it will be clear exactly which protocol the application running in the far uses. Debugging will be easier
=> Added debug message

WinPort/src/Backend/WX/Mac/init.mm
Junk control characters appear in command line on arrows, backspace etc press after invoking quick view because native Ctrl-Q handling is enabled by default, see NSQuotedKeystrokeBinding  on  https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/TextDefaultsBindings/TextDefaultsBindings.html
=> macOS WX: junk control chars on Ctrl-Q

NetRocks/src/Protocol/AWS/S3Repository.cpp
This PR fixes the problems listed in #2785:
- Implements pagination for ListBuckets and ListObjectsV2
- Uses "/" delimiter in ListObjectsV2 to directly get directories and files
- Removes size calculation for folders (because that takes forever in buckets with a lots of files).
=> Fix AWS problems from #2785

incsrch/control.c
The code is disabled and dead, but triggers static analyzer.
=> Fix title overlow in disabled viewer support code. NFC.

DUMPER.md, utils/include/debug.h
1. `std::codecvt_utf8`  has been replaced with calls to `Wide2MB()` and `StrWide2MB()` (no more **'codecvt_utf8<wchar_t>' is deprecated** warnings).
2. Boolean values are now logged in alphanumeric format (`true` and `false` instead of `1` and `0`).
3. All Russian comments have been replaced with their English translations.
4. Minor changes to DUMPER.md.
=> debug dumper updates

far2l/src/vmenu.cpp
idea from Telegram chat: https://t.me/far2l_ru/47287
=> Use '*' as checkmark in NoGraphics mode (-ag or -an)

DUMPER.md, utils/include/debug.h
Добавляет в отладочный дампер возможность получать стек вызовов:
```cpp
DUMP(DSTACKTRACE());
```
На данный момент использует `backtrace()`, `dladdr()` и `abi::__cxa_demangle()`. Код максимально обложен #ifdef-ами.
~~Поскольку для полезного и красивого стека нужны опции -fno-omit-frame-pointer, -fvisibility=default и -rdynamic, был также обновлён файл CMakeLists.txt. Пока что данные настройки применяются только к цели far2l, в Debug-сборке и при явном задании CMake опции -DDUMPER_STACKTRACE_SUPPORT=ON.~~
В качестве метода резолвинга символов добавлен прямой парсинг .symtab/.strtab. На выбор доступно 4 стратегии: юзать только .dynsym, либо только .symtab, либо одну из них с фолбэком к другой.
=> debug dumper: add stacktrace support

DUMPER.md, utils/include/debug.h
1. Добавлена поддержка atos для MacOS.
2. Улучшена группировка команд addr2line / atos, теперь они сохраняют порядок фреймов в стеке, объединяясь не просто по имени модуля, а по последовательностям вызовов функций из одного и того же модуля.
3. Рефакторинг.
4. Try to fix #2843
=> debug dumper: add atos for macOS; improve command grouping; refactor

far2l/src/edit.cpp
Issue:
> Вызываем какой-нибудь диалог с полем редактирования, например Make Folder. Мышью выделяем текст справа налево вплоть до начального символа текста (если там есть текст) и продолжаем удерживать левую кнопку мыши. Начинается скроллинг вправо, и в поле ввода появляется мусор.
=> fix mouse selection beyond left border of an edit

CMakeLists.txt, WinPort/src/Backend/WX/CMakeLists.txt, WinPort/src/Backend/WX/Mac/displaynotify.mm, far2l/CMakeLists.txt
1. Fix build failures on macOS due to flags passed from CMakeLists.
2. Allow a user to choose wx version on macOS, like it is done for FreeBSD.
3. Fix compile error on < 10.8, `NSUserNotification` does not exist prior to it: https://developer.apple.com/documentation/foundation/nsusernotification
=> A few build fixes for macOS

far2l/src/vt/vtshell_translation_kitty.cpp
According to the spec, we should report num and caps always
=> Follow kitty keyboard protocol spec better

far2l/src/panels/filelist.cpp
=> Always prepend filename with ./ when pasting to cmd line

arclite/src/Patch7zCP.cpp
Do not use the 'dlinfo' function when building arclite plugin with uClibc-ng, as this function is not present in the library.
=> Make arclite plugin compatible with uClibc-ng

far2l/src/console/keyboard.cpp
Partially from: https://github.com/shmuz/far2m/commit/2706939c01c102cc20e504918b47210ebd2491a6
`ReadKey` and `GrayKey` didn't do anything useful in the code - deleted; `RightShiftPressedLast` didn't work because the WinApi only had VK_SHIFT for both shift keys - commented.
---
@elfmz возможно для far2l также имеет смысл использовать PVS-Studio?
Для open-source они дают бесплатную лицензию при условии указания их в README - подробности в https://pvs-studio.com/en/order/open-source-license/ Но наверное связываться с ними стоит Вам как основному разработчику, если это интересно.
=> keyboard.cpp - Fix some PVS-Studio warnings (from far2m)

hexitor/src/editor.cpp, hexitor/src/editor.h, hexitor/src/hex_ctl.cpp, hexitor/src/hex_ctl.h
Better UTF-8 awareness to hexitor’s edition and display logic:
- Implemented correct left/right cursor movement over UTF-8 characters
- Highlight all bytes of the current UTF-8 character in the text view
- Improved character replacement logic: overwrite next char if current char is longer in bytes then replaced one, pad with null bytes when new character is shorter,  advance cursor correctly for continuous typing
- Disabled the DELETE key to avoid unexpected behavior
- Fixed get_current_value() to use offset instead of _cursor_offset
=> Add UTF-8 cursor movement, correct character editing, and better highlighting support in Hexitor
