.travis.yml

This make it easier to catch build failures.

Automatic tests / builds with Travis

---

far2l/execute.cpp
far2l/filelist.cpp

Починил https://github.com/elfmz/far2l/issues/22

fix execute binaries with spaces in names

---

far2l/execute.cpp

По проблеме https://github.com/elfmz/far2l/issues/22 , теперь не только пробелы работают, но и другие спец символы, кроме ".

use shell strong quotes for more special chars in names

---

WinPort/APIClipboard.cpp
WinPort/APIFSNotify.cpp
WinPort/APIOther.cpp
WinPort/APIPrintFormat.cpp
WinPort/APIRegistry.cpp
WinPort/APIStringMap.cpp
WinPort/APITime.cpp
WinPort/ConsoleBuffer.cpp
WinPort/ConsoleOutput.cpp
WinPort/KeyFileHelper.cpp
WinPort/WinCompat.h

Начал собирать под macos. WinPort уже собирается.

macosx compatibility

---

far2l/config.cpp
far2l/console.cpp
far2l/copy.cpp
far2l/dialog.cpp
far2l/drivemix.cpp
far2l/farrtl.cpp
far2l/farrtl.hpp
far2l/fileattr.cpp
far2l/findfile.cpp
far2l/headers.hpp
far2l/interf.cpp
far2l/main.cpp
far2l/mkdir.cpp
far2l/savescr.cpp
far2l/scrbuf.cpp
far2l/usermenu.cpp
far2l/wrap.cpp

Теперь и far2l компилится под macos. Глючные русские комменты надо бы поправить.
А линкер теперь ругается на --whole-archive:
```
ld: unknown option: --whole-archive
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../Build/far2l] Error 1
make: *** [All] Error 2
```

far2l macosx compatibility

---

WinPort/APIRegistry.cpp

do not report mkdir fail if path already exists

---

far2l/execute.cpp

Фикс для https://github.com/elfmz/far2l/issues/41

fix fish shell

---

colorer/colorer.project
colorer/src/zlib/contrib/minizip/ioapi.c

Colorer теперь собирается, но не линкуется, не хочет винпортовые анрезолведы оставлять.

macos compatibility

---

farftp/src/ConnectCmds.cpp
farftp/src/FStdLib/all_far.h

farftp macos compatibility

---

multiarc/src/ArcMix.cpp
multiarc/src/ArcProc.cpp
multiarc/src/MultiArc.cpp
multiarc/src/MultiArc.hpp
multiarc/src/arcget.cpp
multiarc/src/arcread.cpp
multiarc/src/formats/7z/7z.cpp
multiarc/src/formats/ace/ace.cpp
multiarc/src/formats/custom/custom.cpp

Теперь multiarc. Из обнаруженных проблем - не расцвечиваются файлы на панели, при ресайзе окна не ресайзится консоль.

multiarc macos compatibility

---

macify_projects.sh

Сделал скрипт преобразования проектов для мака.

add macify_projects.sh script

---

far2l/filepanels.cpp
far2l/filestr.cpp

ещё пара файлов с битой кириллицей (fix #45 )

fix-comment-encoding-4

---

multiarc/src/formats/custom/custom.cpp

StringList из custom интерферировал с StringList из rar.

multiarc: fix crash with rar files

---

far2l/bootstrap/scripts/farlang.templ.m4
far2l/codepage.cpp
far2l/config.cpp
far2l/config.hpp
far2l/fileedit.cpp
far2l/macro.cpp
far2l/viewer.cpp

alternative to default utf8 is koi8r

replace "use ansi as default" with "use utf8 as default".

---

editcase/src/EditCase.cpp
far2l/flshow.cpp

Fix compilation under macOS X.

macOS compilation fixes

---

far2l/viewer.cpp

cycleg-viewer.cpp.diff.zip

---

.travis.yml

These could be uploaded then
https://docs.travis-ci.com/user/deployment/

.travis.yml:  Add command to .zip binaries

---

README.md

wxWidgets-3.1.0 -> wxWidgets-3.1.1

up version of lib to build on latest macosx

---

README.md

Fixed some spelling, grammar, and punctuation, and improved some of the writing.

Various corrections to README.md

---

multiarc/src/ArcMix.cpp
multiarc/src/MultiArc.hpp
multiarc/src/arccmd.cpp
utils/include/utils.h
utils/src/utils.cpp

fixied some issues with special characters in archive file names

Multiarc refactoring

---

WinPort/src/PathHelpers.cpp

The code quality is kind of irrecoverable, so I mostly copy-pasted the `POpen()` function.
I'm not proud of it, but it does the job and is definitely better than inlining the logic.

#359: Support /etc/paths and /etc/paths.d/ on Mac OS

---

WinPort/src/Backend/TTY/TTYBackend.cpp
WinPort/src/Backend/TTY/TTYInputSequenceParser.cpp
WinPort/src/Backend/WX/wxClipboardBackend.cpp

Compiling backend-separation on Mac

---

colorer/src/pcolorer2/FarEditorSet.cpp
far2l/UCD/CharDistribution.cpp
farftp/src/Connect.cpp
farftp/src/FTPConnect.cpp
farftp/src/cnInit.cpp

Осталось ещё одно место где va_end() не хватает, это https://github.com/elfmz/far2l/blob/master/FARStdlib/src/fstd_String.cpp#L139 Но там я сомневаюсь - довольно странно выглядят строки 145-146.

Add missed va_end() call

---

.travis.yml
Brewfile

I'm not sure why there is one unwanted additional job for linux.

add macos to travis, closes #381

---

far2l/TPreRedrawFunc.cpp
far2l/dialog.cpp

https://en.cppreference.com/w/cpp/memory/new/nothrow

Check against nullptr - nothrow added

---

WinPort/src/UI/Paint.cpp
farftp/src/Ftp.cpp

Вроде логику работы сохранил, работать должно аналогично предидущему состоянию)

Fix: realloc mistake: nulled but not freed upon failure

---

farftp/src/Mix.cpp

Попутно вопрос, тут понятно что только оформление и синтаксис, меньше шума при компиляции. Все остальные подобные замечания остались в multiarc. Он планируется к обновлению из внешних источников? Нет желания просто проделывать работу в пустую.

Fix gcc Wdangling-else

---

far2l/datetime.cpp
far2l/filefilterparams.cpp
far2l/findfile.cpp
far2l/strmix.cpp

Это по сути пробник, первое что под руку попалось - constexpr и uint(-1) подлежат приведению в порядок?

Wip: cleanup

---

far2l/PluginA.cpp
far2l/PluginW.cpp
far2l/TPreRedrawFunc.cpp
far2l/interf.cpp
far2l/keyboard.cpp
far2l/keyboard.hpp
far2l/macro.cpp
far2l/macro.hpp
far2l/plugapi.cpp
far2l/strmix.cpp
far2l/strmix.hpp
far2l/vmenu.cpp
far2l/vtansi.cpp
far2l/wrap.cpp

По изменениям не очень зометно, но в IDE порядком ушло implicit кастов...

Key is unsigned, less casts in code

---

WinPort/src/Backend/WX/ExclusiveHotkeys.cpp
WinPort/src/Backend/WX/ExclusiveHotkeys.h
far2l/dialog.cpp
far2l/infolist.cpp
far2l/viewer.cpp
far2l/wrap.cpp

There are more where these came from, but these are the most prominent.

some warnings on Apple

---

far2l/farwinapi.cpp
far2l/farwinapi.hpp
far2l/viewer.hpp

optimize file seeks in viewer's text search

---

far2l/bootstrap/trash.sh

use gio trash if gvfs-trash is not available

---

far2l/dirmix.cpp
far2l/execute.cpp
far2l/infolist.cpp
far2l/panel.cpp
far2l/setattr.cpp
far2l/vtshell.cpp
inside/src/Commands.cpp
utils/include/utils.h
utils/src/utils.cpp

Попытка решить проблемы работы с архивами, файлами и каталогами, имена которых содержат символы "$" и "`", а также выполнения команд в таких каталогах.

Fix some special signs (dollar, back quote) in Multiarc and command shell

---

python/configs/plug/far2l/plugin.hpp
python/configs/plug/far2l/plugin.py
python/configs/plug/far2l/pluginmanager.py
python/configs/plug/far2l/ucharmap.py
python/configs/plug/far2l/udialog.py
python/configs/plug/far2l/upanel.py

Correct display in the "Character Map" dialog, correct handling of buttons and mice.
Sample VFS plugin

python plugin

---

far2l/edit.cpp

Funny off-by-ones no longer прокатывают.

Fixed crash in whole word search

---

NetRocks/src/Protocol/FTP/FTPConnection.cpp
NetRocks/src/Protocol/FTP/FTPConnection.h
NetRocks/src/Protocol/FTP/ProtocolFTP.cpp
NetRocks/src/Protocol/FTP/ProtocolFTP.h
WinPort/src/Backend/TTY/TTYBackend.cpp
WinPort/src/Backend/TTY/TTYBackend.h
WinPort/src/Backend/TTY/TTYInput.cpp
WinPort/src/Backend/TTY/TTYInput.h
WinPort/src/Backend/TTY/TTYInputSequenceParser.cpp
WinPort/src/Backend/TTY/TTYInputSequenceParser.h
WinPort/src/Backend/WinPortMain.cpp

TTY/non-far2l: --ee argument to avoid double escape presses, fix some issues in putty 
NetRocks/FTP: refactor and compatibility improvements

some improvements in TTY/non-far2l and NetRocks/FTP

---

python/configs/plug/far2l/plugin.hpp
python/configs/plug/far2l/plugin.py
python/configs/plug/far2l/ucharmap.py
python/configs/plug/far2l/upanel.py

charmap - after pressing the enter key, copies the selected character to the clipboard
panel - can delete the assigned element(s)
far standard functions (FSF) had an incorrect number of elements

python - charmap, panel

---

far2l/vtshell.cpp

Current implementation skips only one line of output when receives output of shell command.
Which in standard case contains "magic" call with $FARVTRESULT and completion marker.
But in some shells like ZSH with OhMyZsh installed, the output of command may contain a lot of ANSI sequences and have more than one line, causing this "magic" call to appear  in console. 
Idea is to add output "starting" marker, additionally to completion marker, so parser could ignore everything up to starting marker and then copy output until completion marker.

Fix detection of output of commands executed in non-bash shells

---

WinPort/src/Backend/WX/Paint.cpp

E.g. if font size = 13, one char in a string has width 9px (getExtent() returns 9), but total string width is less than N*9px. It causes rendering artifacts when render buffering is enabled. Idea is to disable buffering for certain font sizes as it is done for non-monospaced fonts:
I haven't checked this issue in Linux but in MacOS it surely has a place.
I found "nobufferring" option first of all and enabled it, which fixed this issue, but I think this case could be easily detected in the code, which is my PR is all about.

Fix rendering of fonts with fractional width

---

far2l/vtansi.cpp

fix for https://github.com/elfmz/far2l/issues/792

fix background color brightness support in internal VTE

---

colorer/src/pcolorer2/FarEditorSet.cpp

fixes https://github.com/elfmz/far2l/issues/798

commented out unneeded double push in colorer scheme selection menu

---

colorer/src/Colorer-library/src/colorer/common/Exception.cpp
colorer/src/Colorer-library/src/colorer/xml/XmlInputSource.cpp

#796: Opening editor terminates far2l (symbol not found). Couple of warnings.

---

README.md

It seems like no one write build instructions on Gentoo yet, so I did it yourself.
This PR is logical continue of https://github.com/elfmz/far2l/issues/771#issuecomment-713410516

Support Gentoo-based distros

---

CMakeLists.txt
README.md

This is what got it building for me in the latest version.

Routine MacPorts build update.

---

CMakeLists.txt

Copied a brew's libarchive hack for MacPorts.

#797: workaround for macports' problem with libarchive.

---

README.md

`unxed` said I should probably write this down somewhere. This looks like the place.

Add readme for NixOS builds, and how to update package.

---

far2l/SafeMMap.cpp

SafeMMap::SafeMMap: check mmap return value

SafeMMap: bugfix: check mmap return value

---

WinPort/CMakeLists.txt
WinPort/src/Backend/WX/Mac/pasteboard.h
WinPort/src/Backend/WX/Mac/pasteboard.mm
WinPort/src/Backend/WX/wxClipboardBackend.cpp

I got tired of rebasing my hack on top of master, and finally made another one, a bit less horrible.
Still will not help if `far2l` copies anything but text into a clipboard (I think?..)

#698: pasteboard hack.

---

far2l/bootstrap/view.sh

Added more file types to process by view.sh in internal viewer

View.sh update with more file types

---

far2l/bootstrap/view.sh

Added more file types to process by view.sh in internal viewer

View.sh update with more file types and various enhancements

---

far2l/bootstrap/view.sh

Fixed view of some file types to process by view.sh in internal viewer

View.sh update with various fixes

---

README.md

Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

update mac brew install instructions, closes #983

---

python/configs/plug/far2l/plugin.py
python/configs/plug/far2l/pluginmanager.py
python/configs/plug/plugins/read-en.txt
python/configs/plug/plugins/udialog.py

Adding used identifiers, error in documentation.
Change in line handling with loading extensions.

minor fixes

---

CMakeLists.txt

Make the version compliant with the debian packaging rules

---

python/configs/plug/far2l/fardialogbuilder.py
python/configs/plug/far2l/pluginmanager.py
python/configs/plug/plugins/.vscode/c_cpp_properties.json
python/configs/plug/plugins/.vscode/launch.json
python/configs/plug/plugins/.vscode/settings.json
python/configs/plug/plugins/.vscode/tasks.json
python/configs/plug/plugins/usizer.py

Final changes to sizers with usizer.py example

python - sizers

---

NetRocks/src/Host/HostLocal.cpp
WinPort/WinPort.h
WinPort/src/APIFiles.cpp
far2l/CMakeLists.txt
far2l/FilesSuggestor.cpp
far2l/FilesSuggestor.hpp
far2l/copy.cpp
far2l/copy.hpp
far2l/edit.cpp
far2l/edit.hpp
far2l/farwinapi.cpp
far2l/farwinapi.hpp
far2l/fileedit.cpp
far2l/fileowner.hpp
far2l/flupdate.cpp
far2l/viewer.cpp
far2l/vmenu.cpp
far2l/vmenu.hpp

- fixed error when reading last fragment of CIFS-mounted files
- some IO optimizations to improve file copy speed
- populate autocompletion suggestions list asynchronously from separate thread to avoid long input lags

fix reading CIFS mounted files and implement some optimizations

---

.travis.yml
README.md

Remake of #1080, which I can't reopen after force-push :(
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

Simplify build instructions

---

packaging/suse/far2l.spec

Initiial and simple SPEC for rpm-based distros (tested on openSUSE Tumbleweed). Possibly good starting point for support SuSE/Fedora/CentOS/whatsoever.

Initial version of the openSuSE spec file

---

far2l/bootstrap/mounts.sh

Remove some Mac-specific internal directories not really needed in Drives menu.

Mac: remove some Mac-specific garbage directories from drives menu.

---

python/configs/plug/far2l/fardialog.py
python/configs/plug/plugins/far2lpackages/googletranslate.py
python/configs/plug/plugins/usizer.py
python/configs/plug/plugins/utranslate.py

Useful daily plug-in - translator or spellchecker.
Can be used from the command line and in the editor.

next python plugin

---

far2l/src/filestr.cpp

fix silent data loss then opening some ANSI/OEM files as UTF-8

---

NetRocks/src/NetRocks.cpp
editorcomp/src/editorcomp.cpp

This fixes #1297.
Мне казалось, что проблема в Фаре (один из коммитов 20-го февраля), но проблема была в двух плагинах.
Однако до коммита 20-го февраля проблема вроде не проявлялась.

Fix plugin titles in the menus

---

far2l/bootstrap/mounts.sh

fixed mounts sh freezing for network mounts

---

README.md

Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

Update readme to reflect new python version in brew formula

---

far2l/bootstrap/mounts.sh

resolves issue #1315
P.S. what about user regexes in mounts.sh ?

update mounts.sh regex - exclude tmp mounts

---

far2l/src/panel.cpp

Description: https://forum.farmanager.com/viewtopic.php?t=7915
Fix is made similar to: https://github.com/FarGroup/FarManager/commit/0d4d3273a06276e057c3467ab6f7ab5e1369beaf

Update quick view panel after removing viewed file from temporary panel

---

far2l/src/vt/vtshell.cpp

do not copy OSC 52's clipboard as vertical block

---

WinPort/WinPort.h
WinPort/src/Backend/Backend.h
WinPort/src/Backend/TTY/TTYInputSequenceParser.cpp
WinPort/src/Backend/TTY/TTYOutput.cpp
WinPort/src/Backend/WinPortMain.cpp
far2l/src/console/keyboard.cpp
far2l/src/console/keyboard.hpp
far2l/src/editor.cpp
far2l/src/vt/vtansi.cpp
far2l/src/vt/vtshell.cpp

Support "bracketed paste" mode in VT and TTY backend

---

WinPort/FarTTY.h
WinPort/src/Backend/TTY/TTYBackend.cpp
WinPort/src/Backend/TTY/TTYX/TTYX.cpp
far2l/src/vt/VTFar2lExtensios.cpp

also re-enables compact input mode

kb layout independent keystroke info for tty backend also. see #1562

---

WinPort/src/Backend/TTY/TTYInputSequenceParser.cpp
WinPort/src/Backend/TTY/TTYOutput.cpp
far2l/src/vt/IVTShell.h
far2l/src/vt/vtansi.cpp
far2l/src/vt/vtshell.cpp

as described in spec:
https://github.com/microsoft/terminal/blob/main/doc/specs/%234999%20-%20Improved%20keyboard%20handling%20in%20Conpty.md
available in recent Windows Terminal:
https://github.com/microsoft/terminal/pull/6309

support win32-input-mode

---

WinPort/src/Backend/TTY/TTYX/TTYX.cpp
WinPort/src/Backend/WX/wxWinTranslations.cpp

I understood how to do this with the xkbcommon API, but didn't want to add a new dependency. Luckily, ChatGPT 4 was able to tell me how to do the same on a pure x11 api. Genius tool :)

latin key guess to work even if english kb layout not installed

---

WinPort/src/Backend/TTY/TTYX/TTYX.cpp
WinPort/src/Backend/WX/wxWinTranslations.cpp

fix for older compilers

---

NetRocks/src/UI/Activities/SimpleOperationProgress.cpp
NetRocks/src/UI/Settings/ConfigurePlugin.cpp
WinPort/src/APIConsole.cpp
WinPort/src/Backend/WX/ExclusiveHotkeys.h
inside/src/elf/Dumper.h
utils/include/BitTwiddle.hpp
utils/src/Threaded.cpp
utils/src/ThreadedWorkQueue.cpp

Added few #includes so that the project builds using gcc 13 and clang 16.

Compilation fixes with recent compiler versions (GCC 13, clang 16).

---

WinPort/src/Backend/TTY/TTYX/TTYX.cpp
python/configs/plug/far2l/__init__.py
python/configs/plug/far2l/fardialogbuilder.py
python/configs/plug/far2l/plugin.py
python/configs/plug/far2l/pluginmanager.py
python/configs/plug/plugins/uadb.py
python/configs/plug/plugins/usizer.py
python/src/python.cpp

improvements required by the adb plugin, and the plugin itself works significantly faster
- busybox vs toolbox vs toybox vs pure adb api
- configuration stored in ini file

python adb

---

python/src/python.cpp

I compile python separately and use ready python-venv, sorry.

adb undefined variable

---

python/configs/plug/plugins/udocker.py
python/configs/plug/plugins/udockerio.py

py:load udocker
some methods are still missing: mkdir, rm, rmdir

docker plugin

---

packaging/suse/build-far2l.sh
packaging/suse/far2l.spec
packaging/suse/filter-changelog.py
packaging/suse/git-rpm-changelog.sh
packaging/suse/readme.en.txt

openSUSE: new version of the specs and build scripts, including
1. SPEC fille for openSUSE and Fedora
2. Sample scripts to automate build and changelog generation
3. Readme

openSUSE: new version of the specs and build scripts

---

python/configs/plug/far2l/fardialogbuilder.py
python/configs/plug/plugins/uminer.py

- TEXT has also associated variable name
- simple miner game

changes in python

---

python/configs/plug/far2l/fardialog.py
python/configs/plug/far2l/fardialogbuilder.py
python/configs/plug/far2l/fardialogsizer.py
python/configs/plug/far2l/plugin.py
python/configs/plug/far2l/pluginmanager.py
python/configs/plug/plugins/uadb.py
python/configs/plug/plugins/ucharmap.py
python/configs/plug/plugins/udebug.py
python/configs/plug/plugins/udialog.py
python/configs/plug/plugins/udocker.py
python/configs/plug/plugins/udockerio.py
python/configs/plug/plugins/uinfo.py
python/configs/plug/plugins/uminer.py
python/configs/plug/plugins/upanel.py
python/configs/plug/plugins/usizer.py
python/configs/plug/plugins/utranslate.py

consistent declaration of dialog items

python refactor/reformat

---

far2l/CMakeLists.txt

Create symlink `far2ledit` for use in environment `EDITOR` and as a quick external editor after #1223
This PR partially solve 2. in #1624

Create symlink far2ledit

---

tmppanel/src/TmpClass.cpp

Apply suggestion from #1687

---

CMakeLists.txt

As a workaround for https://github.com/elfmz/far2l/issues/1710

cmake: symlink fix

---

far2l/src/dialog.cpp
far2l/src/fileattr.cpp
far2l/src/fileattr.hpp
far2l/src/setattr.cpp

backport from far2m:
https://github.com/shmuz/far2m/commit/cae499e6d597137682562ea3a966e4f2bec30c32 & https://github.com/shmuz/far2m/commit/5b820ea9c8ba35c65011a197a4b4572ef1e0755e & https://github.com/shmuz/far2m/commit/7a35ba4180b843b5dace9ac0ff25c59680631f97

Attributes dialog: Owner and Group become comboboxes

---

far2l/src/setattr.cpp

Update after #1717
Rewritten Owner and Group lists for obtaining via API
getpwent() ... endpwent() & getgrent() ... endgrent();

Attributes dialog: Owner and Group lists obtaining via API

---

far2l/bootstrap/scripts/FarRus.hlf.m4

В связи с временами всплывающими однотипными вопросами от свежих пользователей (например #1716) набросал на русском черновой раздел справки для новичков.
В нем наверное стоит поправить возможные неточности и сократить лишнее. После раздел можно будет перевести на английский и наверное стоит настроить его показ при первом запуске FAR2L (если такое возможно).
Обсуждать наверное лучше в дискуссии #1598
Также вопрос как из раздела основной помощи ссылаться на раздел из плагина? Код `~Command line and remote FAR2L~@<NetRocks>CommandLine@`  с `<>` не сработал. Неужели он только с абсолютными путями работает?

Help: Особенности FAR2L - начало работы

---

CMakeLists.txt
multiarc/CMakeLists.txt
multiarc/src/ArcPlg.cpp
multiarc/src/formats/custom/custom.cpp

but with no regexp support in config

custom format will work without pcre now

---

far2l/bootstrap/scripts/FarEng.hlf.m4
far2l/bootstrap/scripts/FarRus.hlf.m4

English text improvements after #1771

Help: FAR2L features - Getting Started

---

far2l/src/main.cpp
far2l/src/vt/vtshell.cpp

Backport from far2m https://github.com/shmuz/far2m/commit/522615b7856abdeef53b4be2a444fb6bc8a9990f

Refactoring

---

far2l/src/edit.cpp

One more fix after https://github.com/elfmz/far2l/commit/9dc1b3bb1d82b2c454cfe53e821a32f006df8ae4 & https://github.com/elfmz/far2l/commit/30e12e9d7ea0bc13d55ffe14f9fe97bda57d0da4
Backport from https://github.com/shmuz/far2m/commit/d91b494d323f108948119dab76dbd488b16a4da7

One more fix

---

far2l/src/cfg/ConfigSaveLoad.cpp
far2l/src/cmdline.cpp

`far:about`: change alignment + add OEM/ANSI CP info
`far:config`: * in title when hide unchanged

`far:about` & `far:config`: minor tuning

---

far2l/src/cfg/ConfigSaveLoad.cpp

Так и не разобрался как изменять значения текущего пункта `VMenu` через `VMenu::UpdateItem()`. Сделал через удаление/добавление в ту же позицию пункта.

`far:config` draft Reset to default + refactoring

---

far2l/src/usermenu.cpp

Added ability to execute plugin-commands, i.e. commands with NetRocks via scp on remote servers, from user menu

Execution of plugin commands from user menu (i.e. for NetRocks & scp)

---

far2l/src/cmdline.cpp

New far commands: `far:view:file` `far:view file` `far:edit:file` `far:edit file`

---

far2l/src/cmdline.cpp

Cosmetics after advice https://github.com/elfmz/far2l/pull/1864#issuecomment-1738164683

ProcessFarCommands cosmetics + edit: / far:edit / far:edit: without filename for new file

---

NetRocks/configs/plug/helpe.hlf

based on
https://github.com/elfmz/far2l/issues/247#issuecomment-493710827
https://github.com/elfmz/far2l/issues/247#issuecomment-493738355
С удивлением недавно узнал от @unxed от такой замечательной фиче фонового копирования.
Надеюсь корректно документировал.

NetRocks Help added clearly info about background feature

---

far2l/src/plug/plugapi.cpp

backport from
https://github.com/shmuz/far2m/commit/c73287eeac97c63e4b79bfdd4df11f4a1444f156 & https://github.com/shmuz/far2m/commit/f69edb5aac16631a108a5da99048b9a61dc099f8

plugapi.cpp: dwUnixMode in GetDirList was not set & refactoring near realloc

---

far2l/bootstrap/view.sh

Apply solution from https://github.com/elfmz/far2l/issues/1578#issuecomment-1822265128

chafa - fix #1578

---

far2l/src/editor.cpp

Thank @shmuz for fix in https://github.com/shmuz/far2m/commit/aa09e866475040a80552f7627cb5f4a47a956078

Editor Undo Glitch (from Far3, see FarGroup/FarManager#752)

---

far2l/src/editor.cpp
far2l/src/fileedit.cpp
far2l/src/fileedit.hpp
far2l/src/fileview.cpp
far2l/src/locale/codepage.cpp
far2l/src/locale/codepage.hpp

Fix incorrect reload in Editor & minor Editor/viewer codepage in status bar tuning

---

far2l/src/fileedit.cpp

Thank @shmuz for idea https://github.com/shmuz/far2m/commit/27076d9528fcc57073524df89efe4709687c1896

Workaround for crash #1968

---

far2l/src/vmenu.cpp

Add in list by default info about keys for toggle filtering feature in bottom & Help

---

far2l/src/stddlg.cpp

Вроде подправил некрасивость окна поиска по помощи.
Также прошу обратить внимание на срок выхода очередного релиза для попадания Ubuntu 24.04 LTS - про это ещё раз спросил в https://github.com/elfmz/far2l/issues/692#issuecomment-1934340671

StdDlg GetSearchReplaceString - fix #1995

---

far2l/src/help.cpp
far2l/src/mix/pathmix.cpp
far2l/src/mix/pathmix.hpp
far2l/src/mkdir.cpp

from https://github.com/shmuz/far2m/commit/3304c7b76890733095b70f4fe1f064c22843b781

Refactoring bool DeleteEndSlash() & more clarify buttons in mkdir messages (from far2m)

---

far2l/src/filefilterparams.cpp

Need to redraw

---

WinPort/src/Backend/WX/wxClipboardBackend.cpp

Fixes #2053 (and, probably, #1658).

support data format default on wayland systems for text in utf-8

---

python/configs/plug/plugins/usqlite.py

python usqlite view row data

---

WinPort/src/Backend/WX/wxMain.cpp

just as
https://github.com/elfmz/far2l/pull/2059
but for wx backend

detect Wayland better (on WSLg, for example)

---

python/configs/plug/far2l/pluginmanager.py
python/configs/plug/plugins/ueduniq.py
python/configs/plug/plugins/uuuidgen.py

- proper plugin selection after using F11 menu
- new plugin uuuidgen - UUID generator (uuid is stored in clipboard)
- new plugin ueduniq - make selected lines in editor unique

python plugin update

---

colorer/configs/base/CHANGELOG.md
colorer/configs/base/hrc/base/cpp-qt.hrc
colorer/configs/base/hrc/proto.hrc
colorer/configs/base/hrc/rare/picasm.hrc
colorer/configs/base/hrc/scripts/javacc.hrc
colorer/configs/base/hrc/scripts/makefile.hrc
colorer/configs/base/hrc/scripts/shell-bash.hrc
colorer/configs/base/hrc/scripts/shell-posix.hrc

Updated colorer schema library to the current one on 03/23/2023.
https://github.com/elfmz/far2l/issues/2046

Update Colorer schemes

---

far2l/src/cfg/language.cpp

From https://github.com/shmuz/far2m/commit/ec6809e3ae17b03512d2ce4864583eaf7d84a5c5 & https://github.com/shmuz/far2m/commit/4bbd756e42c94f2b4a3cb2a90d34bac792626f30

Language menus alphabetically sorted (from far2m)

---

WinPort/src/Backend/TTY/TTYOutput.cpp

Fix far2l interface problems under Wezterm

---

calc/src/plugcalc/config.cpp

Fix from #2092 & https://github.com/shmuz/far2m/commit/1b1732f0f6e79f9f5a6c2ca5d5a31742bd119b56

Calc plugin patch (from far2m)

---

WinPort/src/Backend/TTY/TTYInputSequenceParser.cpp
WinPort/src/Backend/TTY/TTYInputSequenceParser.h

- fix elfmz/far2l#2086
- fix swap CTRL and ALT event flags

While mouse button is pressed no longer spam drag events in TTY backend

---

far2l/src/dizlist.cpp

allow to find file "descript.ion", not just file "Descript.ion", etc

Search for file descriptions in any case

---

far2l/src/setattr.cpp

setattr - skip adding duplicates owners & gropus

---

far2l/src/setattr.cpp

Elegant solution from far2m: https://github.com/shmuz/far2m/commit/38e96ba3e968f561b600173476c773bd0713becd & https://github.com/shmuz/far2m/commit/fec81e0a2a6b7d225db41636349920e5d149033f that is better than in #2140

setattr (Attributes dialog): prevent duplicates in Owners/Groups (from far2m)

---

far2l/src/setattr.cpp

Part of https://github.com/shmuz/far2m/commit/f96b04455b02cd59d0beb831f48608cf5849b4fb
Thanks @shmuz

setattr (Attributes dialog): optimize memory (from far2m)

---

.github/workflows/artifacts.yml

Use `_build` dir as in README.md

Simplify Actions workflow

---

multiarc/src/ArcProc.cpp
multiarc/src/arccmd.cpp
multiarc/src/arcget.cpp
multiarc/src/arcput.cpp

fix #1745
Модифицирована логика взведения флага NeedSudo + изменены вызовы конструкторов ArcCommand. В параметр CommandType, на который эта логика ориентировалась, редко приходило что-то адекватное.

fix 1745: some multiarc changes

---

colorer/configs/base/hrc/inet/smarty.hrc
colorer/configs/base/hrc/proto.hrc

Backported 1ef8c8cfc2487a91fff300111638dc5f82f94ddc from Colorer-schemes
See also:
https://github.com/colorer/Colorer-schemes/commit/1ef8c8cfc2487a91fff300111638dc5f82f94ddc
https://github.com/colorer/Colorer-schemes/issues/75

Backported extremely needed for me changes from Colorer-schemes

---

far2l/src/panels/filelist.cpp

Fix #2060
remove unnecessary PrepareDiskPath call, fix error message according to changes

Fix #2060: bug after canceling Privilege elevation and subsequent Retry attempt

---

WinPort/src/Backend/WX/wxMain.cpp

fix Ctrl+ё behavior

---

colorer/src/Colorer-library/src/colorer/utils/Environment.cpp

build on openwrt

---

multiarc/configs/plug/custom.ini

Add support for UDF ISO archives and fix 7z call parameters in custom.ini. Tested on ISO, VDI, SQUASHFS, MSI archives.

Add support for UDF ISO archives and fix custom.ini

---

far2l/bootstrap/scripts/farlang.templ.m4
far2l/src/setattr.cpp

Attributes dialog CtrlA: explanation surprise situation with symlinks properties

---

.github/workflows/build.yml

typo in build.yml

---

far2l/src/mix/processname.cpp

Неучтённый случай с маской формата "[x]".

CmpName_Body: handle one missed case + minor style

---

NetRocks/src/UI/Settings/ConfigurePlugin.cpp

NetRocks: cosmetic

---

far2l/bootstrap/scripts/farlang.templ.m4
far2l/src/cmdline.cpp

* far:about add wsl env
* translate note close to menu item name

miscellaneous tiny commits

---

.github/workflows/build.yml
.github/workflows/clean_workflow.yml

GitHub Action: clean workflow runs

---

far2l/src/panels/filelist.cpp

+, -, * behavior like in mc in TTY and TTY|X modes

---

far2l/bootstrap/scripts/FarEng.hlf.m4
far2l/bootstrap/scripts/FarHun.hlf.m4
far2l/bootstrap/scripts/FarRus.hlf.m4
far2l/bootstrap/scripts/FarUkr.hlf.m4
far2l/src/cmdline.cpp
far2l/src/execute.cpp
far2l/src/execute.hpp
far2l/src/main.cpp

also make ExecuteCommandAndGrabItsOutput global & move from main.cpp to execute.cpp

Add special commands edit:< and view:< for grab redirect output

---

far2l/bootstrap/scripts/farlang.templ.m4
far2l/src/cfg/ConfigOpt.cpp
far2l/src/cfg/config.cpp
far2l/src/cfg/config.hpp
far2l/src/console/interf.cpp
far2l/src/console/interf.hpp
far2l/src/filefilterparams.cpp
far2l/src/hilight.cpp
far2l/src/hilight.hpp
far2l/src/panels/filelist.cpp
far2l/src/panels/filelist.hpp
far2l/src/panels/flshow.cpp
far2l/src/panels/flupdate.cpp
far2l/src/setcolor.cpp
far2l/src/usermenu.cpp

Add align filenames by marks

---

bash-completion/CMakeLists.txt

Wrong path https://github.com/elfmz/far2l/pull/2381#issuecomment-2354609695

fix bash-completion installation path

---

WinPort/src/Backend/TTY/TTYInputSequenceParserExts.cpp

see
https://github.com/microsoft/terminal/issues/17968#issuecomment-2380623291

fix cyrillic chars paste in win32-input-mode

---

NetRocks/src/UI/Settings/ExtraSiteSettings.cpp

fix #2396: NetRocks: Extra connection options, load KeepAlive correctly

---

WinPort/src/Backend/WX/wxWinTranslations.cpp
far2l/src/console/keyboard.cpp

NumLock emulation with Clear button on Apple full size keyboard

---

python/configs/plug/plugins/ugtkhello.py
python/src/python.cpp

/usr/lib/x86_64-linux-gnu/libpython3.11.so comes from python3-dev package, and only python3 (libpython3.11.so.1) can be installed

python - finding usable shared library

---

colorer/configs/base/CHANGELOG.md
colorer/configs/base/hrc/inet/smarty.hrc

https://github.com/colorer/Colorer-schemes/commit/e7166d8c680d4c9b8d19cfda24221298de858963 and
https://github.com/colorer/Colorer-schemes/commit/ee54d177ab9e9da395f38d2cca7831293797c97f
see
https://github.com/colorer/Colorer-schemes/issues/165 for details
touch
https://github.com/elfmz/far2l/pull/2198

backports from colorer

---

far2l/src/base/FARString.hpp
far2l/src/cmdline.cpp

also in FARString.hpp remove incorrect `inline` from Ends() functions

far:about: hide/show empty items + fix incorrect inline in FARString.hpp

---

far2l/src/GrepFile.cpp
utils/src/Escaping.cpp

Fix for 2 issues found when trying to grep "-Wwrite-strings" in a file named #21.txt

Tiny fix for grep in viewer

---

WinPort/src/Backend/WX/wxMain.cpp

https://github.com/wxWidgets/wxWidgets/issues/23421
https://github.com/wxWidgets/wxWidgets/issues/23379
https://github.com/elfmz/far2l/issues/1374
https://github.com/elfmz/far2l/issues/2124
Also fixes #2464

work around some alt+non_latin_letter bugs

---

far2l/src/copy.cpp

fix #2479
from: https://github.com/shmuz/far2m/commit/7cab1950b69b2aaa48c1c8cc1c8b27a96359a7ec

fix 2479: keep directory selection after its renaming

---

WinPort/src/Backend/TTY/TTYInputSequenceParser.cpp

fixed paste in kitty

---

colorer/src/Colorer-library/src/colorer/common/Logger.h
colorer/src/Colorer-library/src/colorer/strings/icu/Encodings.cpp
colorer/src/Colorer-library/src/colorer/strings/icu/Encodings.h
colorer/src/Colorer-library/src/colorer/strings/icu/UStr.cpp
colorer/src/Colorer-library/src/colorer/strings/icu/UStr.h
colorer/src/Colorer-library/src/colorer/strings/legacy/Encodings.cpp
colorer/src/Colorer-library/src/colorer/strings/legacy/Encodings.h
colorer/src/Colorer-library/src/colorer/strings/legacy/UStr.cpp
colorer/src/Colorer-library/src/colorer/strings/legacy/UStr.h
colorer/src/Colorer-library/src/colorer/utils/Environment.cpp
colorer/src/Colorer-library/src/colorer/version.h
colorer/src/Colorer-library/src/colorer/xml/libxml2/LibXmlReader.cpp
colorer/src/Colorer-library/src/colorer/xml/libxml2/SharedXmlInputSource.cpp
colorer/src/pcolorer2/CerrLogger.h

fixed reading catalog.xml if the path contains non-Latin letters

update colorer_lib to 1.4.1

---

tmppanel/src/TmpCfg.cpp
tmppanel/src/TmpCfg.hpp
tmppanel/src/TmpClass.cpp
tmppanel/src/TmpMix.cpp
tmppanel/src/TmpPanel.cpp
tmppanel/src/TmpPanel.hpp

fix #2462
use UTF8 with BOM for list of files

fix #2462: saving file list from tmppanel is broken

---

WinPort/src/Backend/WX/wxMain.cpp
WinPort/src/ConsoleInput.cpp
multiarc/CMakeLists.txt

- fixed alt+letters workaround applying conditions
- fixed keyup event doubling if window focus is lost
- better logging

minor keyboard input fixes

---

colorer/configs/base/CHANGELOG.md
colorer/configs/base/hrc/inet/smarty.hrc
colorer/configs/base/hrc/proto.hrc
colorer/configs/base/hrc/rare/json.hrc
colorer/configs/base/hrc/scripts/dockerfile.hrc
colorer/configs/base/hrc/scripts/hcl/hcl.hrc
colorer/configs/base/hrc/scripts/hcl/terraform.hrc
colorer/configs/base/hrc/scripts/shell-bash.hrc
colorer/configs/base/hrc/scripts/shell-posix.hrc

- fixed error for shell scripts
- changed json
- new syntax !!  dockerfile, hcl, terraform

update colorer schemes to v1.2.0.57

---

WinPort/src/Backend/TTY/TTYBackend.cpp
far2l/src/main.cpp

if this option is available in current environment

Prompt user to allow/disallow OSC52 usage on first run

---

far2l/src/fileedit.cpp
far2l/src/panels/filelist.cpp

from https://github.com/shmuz/far2m/commit/54b65bc913672f6c1022d9f7f990ecf0f2ef7ff1

Allow creation and saving-as filenames containing double quotes

---

far2l/src/delete.cpp
far2l/src/dirinfo.cpp

For deletion progress bar. Fix #1479

Count symlinks as files

---

far2l/bootstrap/scripts/FarEng.hlf.m4
far2l/bootstrap/scripts/FarRus.hlf.m4

Supersedes https://github.com/elfmz/far2l/pull/2562
Workarounds #2551

Add a link to community wiki to Getting Started help topic.

---

far2l/src/viewer.cpp
far2l/src/viewer.hpp

Fix qview crash on broken symlinks

---

WinPort/src/Backend/TTY/TTYOutput.cpp

Fixes #2598
see
https://iterm2.com/documentation-escape-codes.html

fixed iterm2 cursor shape esc sequences

---

README.md
far2l/bootstrap/scripts/FarEng.hlf.m4
far2l/bootstrap/scripts/FarRus.hlf.m4
far2l/bootstrap/scripts/farlang.templ.m4

Возможно пора сделать новогодний релиз - чтобы в Debian попали правильные ярлыки из #2597, уже обкатанные нововведения из огромаднющего #2452 и вроде обкатанные многочисленные фиксы. Или всё-таки ждём когда будет пофиксен #2605?

readme & help + arrange keys in menu

---

far2l/src/hilight.cpp

fix #2605
see https://github.com/elfmz/far2l/issues/2605#issuecomment-2567353455

fix #2605: files highlighting and sort groups bugs

---

HACKING.md
far2l/src/dialog.cpp
far2l/src/dialog.hpp
python/configs/plug/far2l/far2lcffi.py
python/configs/plug/far2l/far2ledit.py
python/configs/plug/far2l/far2lpanel.py
python/configs/plug/far2l/plugin.py
python/configs/plug/far2l/pluginmanager.py
python/configs/plug/plugins/ucharmap.py
python/configs/plug/plugins/udocker.py
python/configs/plug/plugins/uedindent.py
python/configs/plug/plugins/uhexedit.py
python/configs/plug/plugins/usizer.py
python/configs/plug/plugins/usqlite.py

shift/alt/ctrl keys state is not passed to the dialog handler

extending python api - keyboard state for full screen dialogs like hexeditor

---

far2l/src/chattr.cpp
far2l/src/setattr.cpp

prevent blinking in attributes and flags dialogs

---

far2l/src/panels/filelist.cpp

Revert #2643
Not working in plain TTY actually

Revert #2643

---

far2l/src/viewer.cpp

fix #2588 "При поиске просмотрщик без необходимости смещается по горизонтали".

fix #2588: more accurate adjustment of LeftPos in Viewer

---

utils/src/utils.cpp

Handling mulribyte characters on path abbreviation

---

far2l/src/edit.cpp

Various non-printable characters on F5 ShwSpc

---

WinPort/src/Backend/WX/wxWinTranslations.cpp
changelog.md

fixes #2721

---

far2l/src/panels/flshow.cpp

Real cells count for correct extension alignment

---

far2l/src/cmdline.cpp
far2l/src/mix/strmix.cpp
far2l/src/mix/strmix.hpp

thanks @shmuz for idea in https://github.com/shmuz/far2m/commit/9f4fd9113365cf905fe8f6c4998d32a0908257a3

Remove trailing spaces from commands and commands history (from far2m)

---

changelog.md

As requested in https://github.com/elfmz/far2l/pull/2729

NetRocks: update chengelog

---

colorer/src/pcolorer2/FarEditorSet.cpp
colorer/src/pcolorer2/FarEditorSet.h

enable colorer truemod since 8-bit console color palette

---

changelog.md
colorer/configs/base/hrc/base/pascal.hrc
colorer/configs/base/hrc/misc/markdown.hrc
colorer/configs/base/hrc/proto.hrc
colorer/configs/base/hrc/scripts/dfm.hrc
colorer/src/Colorer-library/src/colorer/parsers/KeywordList.cpp

update Colorer library to latest - fixed an important error in the operation of keywords.
update schema to latest

Colorer update

---

NetRocks/src/Op/OpXfer.cpp
NetRocks/src/PluginImpl.cpp
NetRocks/src/Protocol/SSH/ProtocolSCP.cpp
NetRocks/src/SitesConfig.cpp
NetRocks/src/SitesConfig.h
NetRocks/src/UI/Activities/ConfirmXfer.cpp
WinPort/src/Backend/TTY/TTYRevive.cpp
WinPort/src/Backend/WX/Paint.cpp
far2l/src/cfg/config.cpp
far2l/src/main.cpp
far2l/src/plug/PluginA.cpp
far2l/src/plug/PluginW.cpp
far2l/src/setattr.cpp
inside/src/elf/Dumper.cpp

Some optimization from PVS-Studio

PVS-Studio optimization

---

colorer/src/pcolorer2/CerrLogger.cpp
colorer/src/pcolorer2/CerrLogger.h
colorer/src/pcolorer2/ChooseTypeMenu.cpp
colorer/src/pcolorer2/ChooseTypeMenu.h
colorer/src/pcolorer2/FarEditor.cpp
colorer/src/pcolorer2/FarEditor.h
colorer/src/pcolorer2/FarEditorSet.cpp
colorer/src/pcolorer2/FarEditorSet.h
colorer/src/pcolorer2/FarHrcSettings.cpp
colorer/src/pcolorer2/FarHrcSettings.h
colorer/src/pcolorer2/pcolorer.cpp
colorer/src/pcolorer2/pcolorer.h
colorer/src/pcolorer2/tools.cpp

Colorer plugin refactoring

---

far2l/bootstrap/scripts/farlang.templ.m4

Renaming black and white to dark

---

changelog.md
colorer/configs/base/CHANGELOG.md
colorer/configs/base/hrc/base/c.hrc
colorer/configs/base/hrc/proto.hrc
colorer/configs/base/hrc/rare/json.hrc
colorer/configs/base/hrc/scripts/cmake/cmake.hrc
colorer/configs/base/hrc/scripts/far/farmenu.hrc
colorer/configs/base/hrc/scripts/powershell.hrc
colorer/configs/base/hrc/scripts/shell-bash.hrc
colorer/configs/base/hrc/scripts/shell-posix.hrc
colorer/configs/base/hrd/rgb/blue.hrd
colorer/configs/base/hrd/rgb/contrib/navy-mirror.hrd

update colorer schemes to v1.2.0.76

Colorer schemes update

---

far2l/bootstrap/scripts/farlang.templ.m4
far2l/src/about.cpp
far2l/src/cfg/ConfigOptEdit.cpp
far2l/src/options.cpp

far:config and far:about in commands menu

---

far2l/DE/generate_metainfo.py

The AppStream metadata format does not support arbitrary links.
Links to issues are possible, but they do not fit well into our Markdown changelog format. So it's better to remove links completely, and preserve only their inner text.
See <https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description> for details.

generate_metainfo: Remove links, keep only their text

---

python/CMakeLists.txt

continuation https://github.com/elfmz/far2l/pull/2739 - control of modification of auxiliary files

python: monitoring changes in auxiliary files

---

multiarc/src/arcput.cpp

multiarc: fix saving archiver switches

---

colorer/src/pcolorer2/FarEditorSet.cpp

fix crash on close settings after change

fix crash on close settings after change

---

arclite/CMakeLists.txt

monitoring changes in auxiliary files and copy them to install

arclite: monitoring changes in auxiliary files

---

NetRocks/src/Location.cpp

Avoid prompt on opening remote directories from folders history

---

far2l/src/cmdline.hpp
far2l/src/filepanels.cpp
far2l/src/macro/macro.cpp
far2l/src/macro/macro.hpp
far2l/src/panels/filelist.cpp
far2l/src/panels/treelist.cpp

Treat whitespace-only input as empty in command line

---

changelog.md
far2l/bootstrap/scripts/farlang.templ.m4
far2l/src/cfg/ConfigOpt.cpp
far2l/src/cfg/config.hpp
far2l/src/cmdline.cpp

Add support for pasting and executing multiline commands

---

OpenWith/src/OpenWith.cpp
OpenWith/src/XDGBasedAppProvider.cpp
OpenWith/src/XDGBasedAppProvider.hpp

1. Adapt "Details" dialog (F3) width to the far2l window width.
2. More accurate and spec-compliant launch command construction.

OpenWith: UI and business logic improvements

---

far2l/src/execute.cpp

Carriage return for multiline commands

---

.github/workflows/build.yml
_ci/Dockerfile.gcc15

- add new macos version
- update excludes
- add clang 20 build
- add gcc 15 build

CI: add new compiler versions

---

colorer/configs/base/CHANGELOG.md
colorer/configs/base/hrc/base/cpp.hrc
colorer/configs/base/hrc/scripts/gen/cmake/cmake.hrc
colorer/src/pcolorer2/FarEditor.cpp

- fix "select region" call from menu
- update schemes 
- #2960

colorer: fix errors

---

NetRocks/src/Host/HostRemoteBroker.cpp
arclite/src/open.cpp
far2l/src/editor.hpp
hexitor/src/editor.cpp
hexitor/src/editor.h
hexitor/src/find_dlg.cpp
hexitor/src/find_dlg.h
hexitor/src/goto_dlg.cpp
multiarc/CMakeLists.txt

Fix warnings in release build
